/**
* name
*/
var hanlder;
(function (hanlder) {
    var ProtocolsEnum = /** @class */ (function () {
        function ProtocolsEnum() {
        }
        ProtocolsEnum.CLogin = 103; // 根据uid登录游戏，特殊协议,不加786432
        ProtocolsEnum.ErrorInfo = 102; //返回登录错误信息   
        ProtocolsEnum.SOnlineAnnounce = 110; // 登录返回命令******特殊协议   
        ProtocolsEnum.CRoleList = 786433; //获取角色列表    
        ProtocolsEnum.SRoleList = 786434; //返回角色列表    
        ProtocolsEnum.CCreateRole = 786435; //创建角色    
        ProtocolsEnum.SCreateRole = 786436; //创建角色返回    
        ProtocolsEnum.CEnterWorld = 786437; //进入游戏    
        ProtocolsEnum.SEnterWorld = 786438; //进入游戏返回    
        ProtocolsEnum.SGameTime = 786439; //广播服务器时间    
        ProtocolsEnum.SCreateRoleError = 786440; //    
        ProtocolsEnum.CAddPointToAttr = 786444; //客户端请求属性加点    
        ProtocolsEnum.SRefreshUserExp = 786445; //通知客户端刷新人物经验    
        ProtocolsEnum.SRefreshHp = 786446; //通知客户端刷新血量    
        ProtocolsEnum.CResetSysConfig = 786447; //客户端请求修改系统设置    
        ProtocolsEnum.SResetSysConfig = 786448; //服务器发送客户端最新的系统设置    
        ProtocolsEnum.CRoleOffline = 786449; // 客户端下线   
        ProtocolsEnum.SRefSmoney = 786450; // 通知客户端刷新储备金   
        ProtocolsEnum.SError = 786451; //    
        ProtocolsEnum.CReqRoleProp = 786453; // 客户端请求其他玩家的某个属性信息   
        ProtocolsEnum.SRetRoleProp = 786454; // 返回玩家请求的属性对应的属性值   
        ProtocolsEnum.SStartPlayCG = 786455; // 返回玩家请求的属性对应的属性值   
        ProtocolsEnum.CEndPlayCG = 786456; //    
        ProtocolsEnum.CBeginnerTip = 786457; //    
        ProtocolsEnum.SBeginnerTip = 786458; //    
        ProtocolsEnum.CBeginnerTipShowed = 786459; //    
        ProtocolsEnum.SShowedBeginnerTips = 786461; //    
        ProtocolsEnum.CReqRoleTeamState = 786464; // 客户端请求其他玩家的组队情况   
        ProtocolsEnum.SAnswerRoleTeamState = 786465; // 返回玩家请求的其他玩家的组队情况   
        ProtocolsEnum.CRequestName = 786474; // 返回玩家请求的其他玩家的组队情况   
        ProtocolsEnum.SGiveName = 786475; // 返回玩家请求的其他玩家的组队情况   
        ProtocolsEnum.SRecommendsNames = 786476; // 创建角色重名时，服务器回给客户端推荐名字   
        ProtocolsEnum.CReturnRoleList = 786477; // 客户端请求返回角色选择界面   
        ProtocolsEnum.SReturnRoleList = 786478; // 服务器发给客户端，允许返回角色选择界面，并发送已有角色信息列表，同SRoleList   
        ProtocolsEnum.CUserOffline = 786479; // 客户端，人物选择界面："退出游戏"，"返回登录界面"，"返回服务器选择"；在排队中："取消排队   
        ProtocolsEnum.SSendQueueInfo = 786480; // 服务器：发送排队信息   
        ProtocolsEnum.SRoleOffline = 786481; // 服务器：通知客户端下线   
        ProtocolsEnum.CReturnToLogin = 786482; // 客户端请求返回登录界面   
        ProtocolsEnum.SReturnLogin = 786483; // 服务器：通知客户端返回登录界面   
        ProtocolsEnum.SSendSlowQueueInfo = 786484; // 服务器：发送缓慢进入排队信息   
        ProtocolsEnum.CRequestRolePos = 786487; // 客户端使用千里寻踪蝶请求玩家坐标   
        ProtocolsEnum.SFirstDayExitGame = 786489; // 客户端使用千里寻踪蝶请求玩家坐标   
        ProtocolsEnum.CPingStat = 786490; // 客户端通告服务器10分钟内ping值 1分钟一个PingStatEntry  
        ProtocolsEnum.CAfterEnterWorld = 786493; // 客户端进入场景完毕   
        ProtocolsEnum.CSetMaxScreenShowNum = 786495; //客户端自动更改同屏显示人数    
        ProtocolsEnum.SGACDKickoutMsg = 786501; // 客户端进入场景完毕   
        ProtocolsEnum.SSendServerMultiExp = 786502; // 发送服务器多倍信息   
        ProtocolsEnum.SSendLoginIp = 786504; // 发送登录IP信息   
        ProtocolsEnum.SRequestUsedNameData = 786505; // 使用改名道具的时候发送这个协议获取曾用名   
        ProtocolsEnum.CModifyRoleName = 786506; // 客户端请求更改名字   
        ProtocolsEnum.SModifyRoleName = 786507; // 客户端请求更改名字   
        ProtocolsEnum.CReqRoleInfo = 786508; // 请求人物信息界面（主要是 几个积分以及大红大蓝的剩余量）  
        ProtocolsEnum.SRspRoleInfo = 786509; // 人物信息界面回复   
        ProtocolsEnum.CSendSn = 786510; // 客户端发送激活码给服务器   
        ProtocolsEnum.SUserNeedActive = 786511; // 如果玩家需要激活,服务器发这个   
        ProtocolsEnum.CReqChargeMoney = 786512; // 客户端发送充值请求给服务器   
        ProtocolsEnum.CNotifyDeviceInfo = 786514; //    
        ProtocolsEnum.SNotifyDeviceInfo = 786515; //    
        ProtocolsEnum.SNotifyShieldState = 786516; //    
        ProtocolsEnum.SGACDKickoutMsg1 = 786519; //    
        ProtocolsEnum.CReqOldName = 786520; // 请求角色曾用名   
        ProtocolsEnum.SServerLevel = 786521; //    
        ProtocolsEnum.STeamVote = 786524; // 客户端进入场景完毕   
        ProtocolsEnum.CTeamVoteAgree = 786525; //    
        ProtocolsEnum.CGetSysConfig = 786526; //客户端请求修改系统设置    
        ProtocolsEnum.SGetSysConfig = 786527; //服务器发送客户端最新的系统设置    
        ProtocolsEnum.SServerIDResponse = 786529; // 跨服相关的协议   
        ProtocolsEnum.CChangePointScheme = 786530; // 客户端请求切换加点方案   
        ProtocolsEnum.SAddPointAttrData = 786531; //    
        ProtocolsEnum.CReqHelpCountView = 786532; // 客户端请求援助统计面板   
        ProtocolsEnum.SReqHelpCountView = 786533; //    
        ProtocolsEnum.CReqColorRoomView = 786534; // 请求人物染色衣橱信息   
        ProtocolsEnum.SReqColorRoomView = 786535; // 返回人物染色衣橱信息   
        ProtocolsEnum.CReqDelColor = 786536; // 删除衣柜配色方案   
        ProtocolsEnum.CReqUseColor = 786538; // 使用染色   
        ProtocolsEnum.SReqUseColor = 786539; // 返回使用染色成功   
        ProtocolsEnum.CReqPointSchemeTime = 786541; // 请求人物切换加点方案次数   
        ProtocolsEnum.SReqUsePetColor = 786544; // 返回宠物染色   
        ProtocolsEnum.CReqUsePetColor = 786545; //    
        ProtocolsEnum.SReqPointSchemeTime = 786542; // 返回人物切换加点方案次数   
        ProtocolsEnum.CSetPilotType = 786543; // 设置适配引导类型   
        ProtocolsEnum.SSetFunOpenClose = 786546; // 设置功能开关   
        ProtocolsEnum.CSendHelpSW = 786547; // 援助声望当前值   
        ProtocolsEnum.SSendHelpSW = 786548; // 援助声望当前值   
        ProtocolsEnum.CGameTime = 786549; // 取服务器时间 by changhao 
        ProtocolsEnum.CKick = 786550; // 踢人 by changhao 
        ProtocolsEnum.CSetLineConfig = 786551; //    
        ProtocolsEnum.SSetLineConfig = 786552; //    
        ProtocolsEnum.CGetCheckCode = 786553; // 得到验证码   
        ProtocolsEnum.SCheckCodeFinishTime = 786560; // 验证码倒计时完成时间点   
        ProtocolsEnum.CBindTel = 786554; // 确认关联手机   
        ProtocolsEnum.SBindTel = 786555; // 确认关联手机返回状态1成功0失败   
        ProtocolsEnum.CUnBindTel = 786556; //解除关联手机    
        ProtocolsEnum.SUnBindTel = 786557; // 解除关联手机返回状态1成功0失败   
        ProtocolsEnum.CGetBindTel = 786558; // 得到关联手机信息   
        ProtocolsEnum.SGetBindTel = 786559; // 返回关联手机信息   
        ProtocolsEnum.CGetBindTelAward = 786561; // 领取绑定手机奖励   
        ProtocolsEnum.SGetBindTelAward = 786562; // 返回绑定手机奖励状态   
        ProtocolsEnum.SBindTelAgain = 786563; // 重新绑定手机   
        ProtocolsEnum.CSetPassword = 786564; // <!-- 道具安全锁 -->设置密码 
        ProtocolsEnum.SSetPassword = 786565; // 返回成功与否   
        ProtocolsEnum.CResetPassword = 786566; // 重新设置密码   
        ProtocolsEnum.SResetPassword = 786567; // 返回成功与否   
        ProtocolsEnum.CDelPassword = 786568; // 解除安全锁   
        ProtocolsEnum.SDelPassword = 786569; // 返回成功与否   
        ProtocolsEnum.CForceDelPassword = 786572; // 强制解除安全锁   
        ProtocolsEnum.SForceDelPassword = 786573; // 解除时间点   
        ProtocolsEnum.CCancelForceDelPassword = 786574; // 取消强制解除安全锁   
        ProtocolsEnum.SCancelForceDelPassword = 786575; // 返回成功与否   
        ProtocolsEnum.COpenGoodLocks = 786576; // 开启安全锁状态   
        ProtocolsEnum.SOpenGoodLocks = 786577; // 返回成功与否   
        ProtocolsEnum.CCloseGoodLocks = 786578; // 关闭安全锁状态   
        ProtocolsEnum.SCloseGoodLocks = 786579; // 返回成功与否   
        ProtocolsEnum.CGetGoodLocksInfo = 786580; // 得到道具安全锁信息   
        ProtocolsEnum.SGetGoodLocksInfo = 786581; //    
        ProtocolsEnum.CGoodUnLock = 786582; // 道具输入密码解锁   
        ProtocolsEnum.SGoodUnLock = 786583; // 道具输入密码解锁状态   
        ProtocolsEnum.CForceUnlockTimeExpire = 786586; // 通知强制解锁到期   
        ProtocolsEnum.SForceUnlockTimeExpire = 786587; // 强制解锁到期状态   
        ProtocolsEnum.SChangeGoodLockState = 786588; // 改变道具锁的状态   
        ProtocolsEnum.CReceiveCheckCode = 786570; //    
        ProtocolsEnum.SCheckCodeFinishTimePoint = 786571; // 验证码倒计时完成时间点   
        ProtocolsEnum.CSendCBGCheckCode = 786584; // <!-- 藏宝阁上架短信验证 -->藏宝阁发送验证码 
        ProtocolsEnum.SCBGUpCheckCode = 786585; // 藏宝阁上架验证   
        ProtocolsEnum.CGetPetEquipInfo = 786592; //    
        ProtocolsEnum.SGetPetEquipInfo = 786593; //    
        ProtocolsEnum.CQueryRegData = 810532; // <!-- 签到开始 --> 
        ProtocolsEnum.SQueryRegData = 810533; //    
        ProtocolsEnum.CReg = 810534; //    
        ProtocolsEnum.festival = 810535; // 请求节日签到数据   
        ProtocolsEnum.SQueryFestivalData = 810536; // 返回节日签到数据   
        ProtocolsEnum.CGetFestivalReward = 810537; // 活动奖励id   
        ProtocolsEnum.CQueryJRAwardData = 810538; // 请求节日活跃度奖励表数据   
        ProtocolsEnum.SQueryJRAwardData = 810539; // 请求节日活跃度奖励表数据   
        ProtocolsEnum.CGetHydAward = 810540; //    
        ProtocolsEnum.CGetChargeAward = 810541; //    
        ProtocolsEnum.CQueryChargeAwardCountData = 810543; // 请求累计充值奖励表数据   
        ProtocolsEnum.SQueryChargeAwardCountData = 810544; // 请求累计充值奖励表数据   
        ProtocolsEnum.CGetChargeAwardCount = 810545; //    
        ProtocolsEnum.CQueryHydScoreData = 810546; //请求节日积分奖励表数据    
        ProtocolsEnum.SQueryHydScoreData = 810547; //请求节日积分奖励表数据    
        ProtocolsEnum.CGetHydScoreAward = 810548; //    
        ProtocolsEnum.CQQExchangeCodeStatus = 819196; //客户端请求QQ会员兑换码状态    
        ProtocolsEnum.SQQExchangeCodeStatus = 819197; //服务端发送QQ会员兑换码状态    
        ProtocolsEnum.CExchangeCode = 819198; //客户端请求兑换兑换码    
        ProtocolsEnum.SExchangeCode = 819199; //服务端返回兑换成功标志    
        ProtocolsEnum.CXMRNPCView = 810582; //请求熊猫人界面    
        ProtocolsEnum.SXMRNPCView = 810583; //请求熊猫人界面    
        ProtocolsEnum.CXMRBossNPCView = 810584; //请求熊猫人boss界面    
        ProtocolsEnum.SXMRBossNPCView = 810585; //请求熊猫人boss界面    
        ProtocolsEnum.CXMRGiveRose = 810586; // 点赞   
        ProtocolsEnum.SXMRGiveRose = 810587; // 点赞   
        ProtocolsEnum.CXMRWatchVideo = 810588; // 观看录像   
        ProtocolsEnum.CXMRWatchFight = 810589; // 观看战斗   
        ProtocolsEnum.SRefreshRoleData = 799432; //<!-- 刷新人物属性的消息-->   
        ProtocolsEnum.SRefreshPetData = 799433; //<!-- 刷新宠物属性的消息-->   
        ProtocolsEnum.SRefreshPointType = 799435; //<!-- 刷新人物加点后的加点面板数值 -->  
        ProtocolsEnum.SRefreshRoleScore = 799436; //<!-- 刷新人物评分的消息-->   
        ProtocolsEnum.SRefreshRoleCurrency = 799437; //刷新人物通货的消息    
        ProtocolsEnum.CApplyYingFuExprience = 799438; //客户端申请角色盈福经验    
        ProtocolsEnum.SApplyYingFuExprience = 799439; //服务器回复角色盈福经验    
        ProtocolsEnum.SSendBattleStart = 793433; // 服务器向客户端发送战斗信息   
        ProtocolsEnum.SSendAddFighters = 793434; // 服务器向客户端发送战斗信息   
        ProtocolsEnum.SSendRoundStart = 793435; // 服务器向客户端发送 开始回合操作选择  
        ProtocolsEnum.CSendAction = 793436; // 客户端向服务器发送操作选择消息   
        ProtocolsEnum.CSendRoundPlayEnd = 793438; // 客户端向服务器发送 剧本播放结束消息  
        ProtocolsEnum.SSendBattleEnd = 793439; // 服务器向客户端发送结束战斗消息   
        ProtocolsEnum.CSendWatchBattle = 793443; // 请求观战   
        ProtocolsEnum.SSendWatchBattleStart = 793444; // 服务器向客户端发送观战开始信息   
        ProtocolsEnum.CEndWatchBattle = 793445; // 请求退出观战   
        ProtocolsEnum.SRemoveWatcher = 793448; // 退出观战的fighter   
        ProtocolsEnum.SSendBattlerOperateState = 793450; //发送人物操作状态（准备中，请等待，掉线）    
        ProtocolsEnum.SSendRoleInitAttrs = 793455; // 服务器发给客户端，进战斗时主角的二级属性   
        ProtocolsEnum.SSendPetInitAttrs = 793456; // 服务器发给客户端，进战斗时主角宠物的二级属性   
        ProtocolsEnum.SSendRoundScript = 793457; // 服务器向客户端发送剧本   
        ProtocolsEnum.SSendAlreadyUseItem = 793458; // 服务器向客户端发送已经使用过的道具列表，baseid   
        ProtocolsEnum.SSynchroBossHp = 793459; // 服务器向客户端发送公会boss血量   
        ProtocolsEnum.SSendRoundPlayEnd = 793462; // 服务器广播给战斗内所有人，某个角色已经播放动画完毕了   
        ProtocolsEnum.CSendInvitePlayPK = 793564; // 邀请某角色进行PK   
        ProtocolsEnum.SDeadLess20 = 793563; //    
        ProtocolsEnum.CReqNewHandBattle = 793584; //    
        ProtocolsEnum.CPvP1MyInfo = 793533; // 客户端请求自己的信息   
        ProtocolsEnum.SPvP1MyInfo = 793534; // 服务器发送自己的信息   
        ProtocolsEnum.CPvP1RankingList = 793535; // 客户端请求排行榜   
        ProtocolsEnum.SPvP1RankingList = 793536; // 服务器发送排行榜   
        ProtocolsEnum.CPvP1ReadyFight = 793538; // 客户端请求准备完毕   
        ProtocolsEnum.SPvP1ReadyFight = 793539; // 服务器发送准备状态   
        ProtocolsEnum.SPvP1BattleInfo = 793540; // 服务器发送场内战斗信息   
        ProtocolsEnum.CPvP1OpenBox = 793541; // 客户端请求打开箱子   
        ProtocolsEnum.SPvP1MatchResult = 793542; // 通知客户端匹配结果   
        ProtocolsEnum.SPvP1OpenBoxState = 793544; // 服务器发送箱子状态   
        ProtocolsEnum.CPvP3MyInfo = 793633; // 客户端请求自己的信息   
        ProtocolsEnum.SPvP3MyInfo = 793634; // 服务器发送自己的信息   
        ProtocolsEnum.CPvP3RankingList = 793635; // 客户端请求排行榜   
        ProtocolsEnum.SPvP3RankingList = 793636; // 服务器发送排行榜   
        ProtocolsEnum.CPvP3ReadyFight = 793643; // 客户端请求准备完毕   
        ProtocolsEnum.SPvP3ReadyFight = 793644; // 服务器发送准备状态   
        ProtocolsEnum.SPvP3MatchResult = 793645; // 通知客户端匹配结果   
        ProtocolsEnum.SPvP3BattleInfo = 793646; // 服务器发送场内战斗信息   
        ProtocolsEnum.CPvP3OpenBox = 793653; // 客户端请求打开箱子   
        ProtocolsEnum.SPvP3OpenBoxState = 793654; // 服务器发送箱子状态   
        ProtocolsEnum.CPvP5MyInfo = 793663; // 客户端请求自己的信息   
        ProtocolsEnum.SPvP5MyInfo = 793664; // 服务器发送自己的信息   
        ProtocolsEnum.CPvP5RankingList = 793665; // 客户端请求排行榜   
        ProtocolsEnum.SPvP5RankingList = 793666; // 服务器发送排行榜   
        ProtocolsEnum.SPvP5ReadyFight = 793668; // 服务器发送准备状态   
        ProtocolsEnum.SPvP5MatchResult = 793669; // 通知客户端匹配结果   
        ProtocolsEnum.SPvP5BattleInfo = 793670; // 服务器发送场内战斗信息   
        ProtocolsEnum.CPvP5OpenBox = 793672; // 客户端请求打开箱子   
        ProtocolsEnum.SPvP5OpenBoxState = 793673; // 服务器发送箱子状态   
        ProtocolsEnum.CPlayPKFightView = 793683; // 寻找对手界面   
        ProtocolsEnum.SPlayPKFightView = 793684; // 返回对手界面   
        ProtocolsEnum.CInvitationPlayPK = 793687; // 发送切磋邀请   
        ProtocolsEnum.SInvitationPlayPK = 793688; //    
        ProtocolsEnum.CInvitationPlayPKResult = 793689; // 是拒绝还是接受切磋   
        ProtocolsEnum.SInvitationPlayPKResult = 793690; // 是拒绝还是接受切磋   
        ProtocolsEnum.CReqCameraUrl = 793733; // 请求录像url   
        ProtocolsEnum.SSendCameraUrl = 793734; // 返回录像url   
        ProtocolsEnum.CReqRePlay = 793735; // 请求播放录像   
        ProtocolsEnum.SReqRePlay = 793736; // 请求播放录像返回   
        ProtocolsEnum.CStopRePlay = 793737; // 停止播放   
        ProtocolsEnum.CInvitationLiveDieBattle = 793833; // 下战书   
        ProtocolsEnum.SInvitationLiveDieBattle = 793834; // 返回下战书   
        ProtocolsEnum.CInvitationLiveDieBattleOK = 793835; // 确定是否下战书   
        ProtocolsEnum.SInvitationLiveDieBattleOK = 793836; // 返回是否接受下战书结果   
        ProtocolsEnum.CAcceptInvitationLiveDieBattle = 793837; // 确定是否接受战书   
        ProtocolsEnum.SAcceptInvitationLiveDieBattle = 793838; // 确定是否接受战书   
        ProtocolsEnum.CAcceptLiveDieBattle = 793839; // npc处应战开战   
        ProtocolsEnum.CLiveDieBattleWatchView = 793840; // 请求生死战观战界面   
        ProtocolsEnum.SLiveDieBattleWatchView = 793841; // 返回请求生死战观战界面   
        ProtocolsEnum.CLiveDieBattleRankView = 793842; // 请求生死战排行界面   
        ProtocolsEnum.SLiveDieBattleRankView = 793843; // 返回请求生死战排行界面   
        ProtocolsEnum.CLiveDieBattleGiveRose = 793844; // 点赞   
        ProtocolsEnum.SLiveDieBattleGiveRose = 793845; // 点赞   
        ProtocolsEnum.CLiveDieBattleWatchVideo = 793846; // 观看录像   
        ProtocolsEnum.CLiveDieBattleWatchFight = 793847; // 观看战斗   
        ProtocolsEnum.CAcceptLiveDieBattleFirst = 793848; // 玩家来应战(第一个确认按钮)   
        ProtocolsEnum.SAcceptLiveDieBattleFirst = 793849; // 返回玩家来应战(第一个确认按钮)   
        ProtocolsEnum.CReqBattleFlag = 793883; //<!-- 战斗指挥being 协议号从7451-7500 --> 
        ProtocolsEnum.SSendBattleFlag = 793884; //    
        ProtocolsEnum.CModifyBattleFlag = 793885; //    
        ProtocolsEnum.SModifyBattleFlag = 793886; //    
        ProtocolsEnum.CSetCommander = 793887; //    
        ProtocolsEnum.SSetCommander = 793888; //    
        ProtocolsEnum.CSetBattleFlag = 793889; //    
        ProtocolsEnum.SSetBattleFlag = 793890; //    
        ProtocolsEnum.SBuffChangeResult = 796442; //buff改变结果更新协议    
        ProtocolsEnum.SRefreshSpecialQuest = 807432; //    
        ProtocolsEnum.SRefreshSpecialQuestState = 807433; //    
        ProtocolsEnum.CAbandonQuest = 807434; //    
        ProtocolsEnum.SRefreshActiveQuest = 807435; //    
        ProtocolsEnum.SSendActiveQuestList = 807436; // 角色上线的时候服务器发给客户端所有当前未完成的任务列表   
        ProtocolsEnum.SRefreshQuestData = 807438; // 任务数据发生变化时，服务器向客户端发送的刷新消息   
        ProtocolsEnum.CQuestionnaireResult = 807444; // 问卷调查答案   
        ProtocolsEnum.SQuestionnaireTitleAndExp = 807445; // 问卷调查获得称号和经验   
        ProtocolsEnum.CReqGotoPatrol = 807446; // 请求跳转到职业巡逻地图   
        ProtocolsEnum.SRenXingCircleTask = 807450; // 服务通知客户端任性   
        ProtocolsEnum.CRenXingCircleTask = 807451; // 客户端选择货币类型任性任务   
        ProtocolsEnum.CQueryCircleTaskState = 807452; // 客户端请求查询任务状态   
        ProtocolsEnum.SQueryCircleTaskState = 807453; // 回复任务状态   
        ProtocolsEnum.SRefreshAnYeData = 807454; //<!-- 暗夜马戏团任务相关 -->  
        ProtocolsEnum.CSubmitThings = 807455; //    
        ProtocolsEnum.CRenXingAnYeTask = 807456; // 任性暗夜马戏团任务   
        ProtocolsEnum.CSetAnYeJoinTime = 807457; // 首次参加时间   
        ProtocolsEnum.CLengendAnYetask = 807458; // 寻宝一个暗夜马戏团任务   
        ProtocolsEnum.SLengendAnYetask = 807459; // 返回寻宝结果   
        ProtocolsEnum.CAbandonAnYe = 807460; // 放弃的任务id(暗夜马戏团1080000)   
        ProtocolsEnum.COpenClanMedic = 808439; //请求药房信息    
        ProtocolsEnum.SOpenClanMedic = 808440; // 返回请求药房信息   
        ProtocolsEnum.CBuyMedic = 808441; // 购买药房的药品   
        ProtocolsEnum.COpenClan = 808446; // 客户端请求公会界面：有公会   
        ProtocolsEnum.COpenClanList = 808447; //客户端请求公会列表：没有公会    
        ProtocolsEnum.SOpenClanList = 808448; //服务端响应客户端请求公会列表协议：没有公会    
        ProtocolsEnum.SOpenClan = 808449; // 服务端响应客户端请求公会界面协议：有公会   
        ProtocolsEnum.CCreateClan = 808450; // 客户端请求创建公会   
        ProtocolsEnum.CLeaveClan = 808451; // 主动脱离公会   
        ProtocolsEnum.SLeaveClan = 808452; // 脱离公会成功,客户端将公会界面关闭   
        ProtocolsEnum.CApplyClan = 808453; // 申请入会   
        ProtocolsEnum.CRequestApplyList = 808454; // 客户端请求申请加入公会的人员列表   
        ProtocolsEnum.CClearApplyList = 808455; // 清除申请者列表   
        ProtocolsEnum.SRequestApply = 808456; // 服务端返回申请加入公会的人员列表   
        ProtocolsEnum.CAcceptOrRefuseApply = 808457; //    
        ProtocolsEnum.SRefuseApply = 808458; // 服务器返回拒绝申请人员   
        ProtocolsEnum.CChangeClanAim = 808459; // 更改宗旨   
        ProtocolsEnum.SChangeClanAim = 808460; // 服务器返回新宗旨   
        ProtocolsEnum.CClanInvitation = 808461; // 公会邀请   
        ProtocolsEnum.SClanInvitation = 808462; // 公会邀请   
        ProtocolsEnum.CChangePosition = 808464; // 更改职务   
        ProtocolsEnum.SRefreshPosition = 808466; // 返回职务   
        ProtocolsEnum.CFireMember = 808467; // 驱逐成员   
        ProtocolsEnum.SFireMember = 808468; // 驱逐成员返回   
        ProtocolsEnum.CClanMessage = 808469; // 发布公会群消息   
        ProtocolsEnum.CAcceptOrRefuseInvitation = 808470; //    
        ProtocolsEnum.CRequestClanLevelup = 808472; // 升级公会大厅，金库，药店，旅馆   
        ProtocolsEnum.SClanLevelup = 808473; // 返回公会级别信息变化 by changhao 
        ProtocolsEnum.CGrabBonus = 808474; // 领取分红 by changhao 
        ProtocolsEnum.SGrabBonus = 808475; // 领取分红 by changhao 
        ProtocolsEnum.CBonusQuery = 808476; // 查询分红   
        ProtocolsEnum.SBonusQuery = 808477; // 查询分红结果   
        ProtocolsEnum.SAcceptApply = 808478; // 服务器返回接受申请人员   
        ProtocolsEnum.CRequestClanAim = 808479; // 客户端请求公会宗旨   
        ProtocolsEnum.SClanAim = 808480; // 服务端返回公会宗旨   
        ProtocolsEnum.CChangeClanName = 808484; // 更改公会名字   
        ProtocolsEnum.SChangeClanName = 808485; // 服务端返回公会名字   
        ProtocolsEnum.CSearchClan = 808486; // 请求搜索公会   
        ProtocolsEnum.SSearchClan = 808487; // 返回搜索公会   
        ProtocolsEnum.COneKeyApplyClan = 808488; // 一键申请   
        ProtocolsEnum.CBannedtalk = 808489; // 禁言   
        ProtocolsEnum.SBannedtalk = 808490; // 禁言   
        ProtocolsEnum.CEnterClanMap = 808491; // 进入公会地图   
        ProtocolsEnum.CRefreshMemberList = 808492; // 请求刷新成员列表   
        ProtocolsEnum.SRefreshMemberList = 808493; // 返回成员列表   
        ProtocolsEnum.SApplyClanList = 808494; // 返回申请过的公会列表   
        ProtocolsEnum.CCancelApplyClan = 808495; // 取消申请公会   
        ProtocolsEnum.SCancelApplyClan = 808496; // 取消申请公会   
        ProtocolsEnum.SRefreshContribution = 808497; // 更新个人帮贡信息   
        ProtocolsEnum.COpenAutoJoinClan = 808498; // 是否开启自动接收入会   
        ProtocolsEnum.SOpenAutoJoinClan = 808499; // 是否开启自动接收入会   
        ProtocolsEnum.CRequestEventInfo = 808500; // 请求公会事件信息   
        ProtocolsEnum.SRequestEventInfo = 808501; // 返回公会事件信息   
        ProtocolsEnum.CRequestRoleInfo = 808502; // 请求公会事件详情信息   
        ProtocolsEnum.SRequestRoleInfo = 808503; // 返回公会事件详情信息   
        ProtocolsEnum.SBuyMedic = 808504; // 返回购买药房的药品   
        ProtocolsEnum.CRequestSelectType = 808505; // 请求修改产药倍数   
        ProtocolsEnum.SRequestSelectType = 808506; // 返回修改产药倍数   
        ProtocolsEnum.CRequestRuneInfo = 808507; // 请求符文请求信息   
        ProtocolsEnum.SRequestRuneInfo = 808508; // 返回请求符文请求信息   
        ProtocolsEnum.CRuneGive = 808509; // 捐献符文   
        ProtocolsEnum.SRuneGive = 808510; // 返回捐献符文   
        ProtocolsEnum.CRuneRequest = 808511; // 请求符文   
        ProtocolsEnum.SRuneRequest = 808512; // 请求符文   
        ProtocolsEnum.CRequestRuneCount = 808513; // 请求符文统计   
        ProtocolsEnum.SRequestRuneCount = 808514; // 返回请求符文统计   
        ProtocolsEnum.CRuneRequestView = 808515; // 请求符文界面   
        ProtocolsEnum.SRuneRequestView = 808516; // 返回请求符文界面   
        ProtocolsEnum.SClanRedTip = 808517; // 通知客户端红点信息 value=0 没有红点 value=1有红点
        ProtocolsEnum.CRefreshRoleClan = 808518; // 客户端请求服务器该玩家是否有公会   
        ProtocolsEnum.SRefreshRoleClan = 808519; // 服务器返回该玩家是否有公会   
        ProtocolsEnum.CClanInvitationView = 808520; // 客户端请求邀请界面   
        ProtocolsEnum.SClanInvitationView = 808521; // 客户端请求邀请界面   
        ProtocolsEnum.CRequestSearchRole = 808522; // 搜索   
        ProtocolsEnum.SRequestSearchRole = 808523; // 搜索好成功   
        ProtocolsEnum.CChangeClanInst = 808524; // 改变公会副本   
        ProtocolsEnum.SChangeClanInst = 808525; // 改变公会副本成功   
        ProtocolsEnum.CRequestImpeachMentView = 808526; // 请求弹劾界面   
        ProtocolsEnum.SRequestImpeachMentView = 808527; // 返回发起界面   
        ProtocolsEnum.CGetClanFightList = 808532; // 得到对战列表   
        ProtocolsEnum.SGetClanFightList = 808533; // 返回对战列表   
        ProtocolsEnum.CStartClanFightBattle = 808534; // 点击进入pk by changhao 
        ProtocolsEnum.CBattleFieldScore = 808535; // 公会战时统计   
        ProtocolsEnum.SBattleFieldScore = 808536; // 公会战时统计   
        ProtocolsEnum.SBattleFieldAct = 808537; // 公会战时统计 by changhao 
        ProtocolsEnum.CBattleFieldRankList = 808538; // 公会战时统计 by changhao 
        ProtocolsEnum.SBattleFieldRankList = 808539; // 公会战时统计 by changhao 
        ProtocolsEnum.SBattleFieldInfo = 808540; // 公会战时信息 by changhao 
        ProtocolsEnum.CRequestRoleIsEnemy = 808541; // 请求是否是敌对 by changhao 
        ProtocolsEnum.SRequestRoleIsEnemy = 808542; // 请求是否是敌对 by changhao 
        ProtocolsEnum.SClanFightOver = 808543; // 战场结束 by changhao 
        ProtocolsEnum.SLeaveBattleField = 808544; // 离开战场 by changhao 
        ProtocolsEnum.CGetClearTime = 808545; // 得到下次清零时间 by changhao 
        ProtocolsEnum.SGetClearTime = 808546; // 得到下次清零时间 by changhao 
        ProtocolsEnum.SendRoleInfo = 811432; // <!-- 跨服和原服之间的协议 start 协议号从25000
        ProtocolsEnum.SendRoleInfo_Rep = 811433; //    
        ProtocolsEnum.SendRoleData = 811434; //    
        ProtocolsEnum.FinishCopyRole = 811435; //    
        ProtocolsEnum.SendWordMsg = 811436; //    
        ProtocolsEnum.SCReqCrosserInfo = 811437; //    
        ProtocolsEnum.CSSendCrosserInfo = 811438; //    
        ProtocolsEnum.SCCreateRoom = 811439; //    
        ProtocolsEnum.SCReqRoomInfos = 811440; //    
        ProtocolsEnum.CSSendRoomInfos = 811441; //    
        ProtocolsEnum.CSUpdataRoomInfo = 811442; //    
        ProtocolsEnum.SCLeaveRoom = 811443; //    
        ProtocolsEnum.CSLeaveRoom = 811444; //    
        ProtocolsEnum.SCStandCross = 811445; //    
        ProtocolsEnum.CSStandCross = 811446; //    
        ProtocolsEnum.SCEnterRoom = 811447; //    
        ProtocolsEnum.CSNotifyMsg = 811448; //    
        ProtocolsEnum.SCRoomStand = 811449; //    
        ProtocolsEnum.CSRoomStand = 811450; //    
        ProtocolsEnum.CSCrossBattleInfo = 811451; //    
        ProtocolsEnum.CSCrossBattleMemberState = 811452; //    
        ProtocolsEnum.CSCrossBattleResult = 811453; //    
        ProtocolsEnum.SCReqRoomInfo = 811454; //    
        ProtocolsEnum.SCChangeCrosserForm = 811455; //    
        ProtocolsEnum.CSChangeCrosserForm = 811456; //    
        ProtocolsEnum.SCChangeRoomPwd = 811457; //    
        ProtocolsEnum.SCModifyCrossMoney = 811458; //    
        ProtocolsEnum.CSCrossMoneyBonus = 811459; //    
        ProtocolsEnum.SCEndCross = 811460; //    
        ProtocolsEnum.CSEndCross = 811461; //    
        ProtocolsEnum.SCReqTTBonus = 811462; //    
        ProtocolsEnum.CSResultTTBonus = 811463; //    
        ProtocolsEnum.SCResultTTBonus = 811464; //    
        ProtocolsEnum.SCInvitJoinRoom = 811465; //    
        ProtocolsEnum.CSInvitJoinRoom = 811466; //    
        ProtocolsEnum.SCReqCrossRankList = 811467; //    
        ProtocolsEnum.CSReqCrossRankList = 811468; //    
        ProtocolsEnum.SCKickoffRoom = 811469; //    
        ProtocolsEnum.CSKickoffRoom = 811470; //    
        ProtocolsEnum.SCAddCrossIntegral = 811471; //    
        ProtocolsEnum.SCCrossLvUp = 811472; //    
        ProtocolsEnum.SCSetRoomOwner = 811473; //    
        ProtocolsEnum.SCSwapRoomMember = 811474; //    
        ProtocolsEnum.CSSwapRoomMember = 811475; //    
        ProtocolsEnum.SBeginCorssServer = 811932; //    
        ProtocolsEnum.CSendAllServerMsg = 811933; //    
        ProtocolsEnum.CReqCrosserInfo = 811934; //    
        ProtocolsEnum.SSendCrosserInfo = 811935; //    
        ProtocolsEnum.CReqRoomInfos = 811936; //    
        ProtocolsEnum.SSendRoomInfos = 811937; //    
        ProtocolsEnum.SUpdataRoomInfo = 811938; //    
        ProtocolsEnum.CLeaveRoom = 811939; //    
        ProtocolsEnum.SLeaveRoom = 811940; //    
        ProtocolsEnum.CStandCross = 811941; //    
        ProtocolsEnum.SStandCross = 811942; //    
        ProtocolsEnum.CCreateRoom = 811943; //    
        ProtocolsEnum.CEnterRoom = 811944; //    
        ProtocolsEnum.SNotifyMsg = 811945; //    
        ProtocolsEnum.CRoomStand = 811946; //    
        ProtocolsEnum.SRoomStand = 811947; //    
        ProtocolsEnum.SCrossBattleInfo = 811948; //    
        ProtocolsEnum.SCrossBattleMemberState = 811949; //    
        ProtocolsEnum.SCrossBattleResult = 811950; //    
        ProtocolsEnum.CChangeCrosserForm = 811951; //    
        ProtocolsEnum.SChangeCrosserForm = 811952; //    
        ProtocolsEnum.CChangeRoomPwd = 811953; //    
        ProtocolsEnum.CEndCross = 811954; //    
        ProtocolsEnum.CReqTTBonus = 811955; //    
        ProtocolsEnum.SResultTTBonus = 811956; //    
        ProtocolsEnum.CInvitJoinRoom = 811957; //    
        ProtocolsEnum.SInvitJoinRoom = 811958; //    
        ProtocolsEnum.CReqCrossRankList = 811959; //    
        ProtocolsEnum.SReqCrossRankList = 811960; //    
        ProtocolsEnum.CKickoffRoom = 811961; //    
        ProtocolsEnum.SKickoffRoom = 811962; //    
        ProtocolsEnum.CEnterLeaveHell = 811963; //    
        ProtocolsEnum.SEnterLeaveHell = 811964; //    
        ProtocolsEnum.CSetRoomOwner = 811965; //    
        ProtocolsEnum.CSwapRoomMember = 811966; //    
        ProtocolsEnum.SSwapRoomMember = 811967; // 请求交换队员   
        ProtocolsEnum.SEndCross = 811968; // 服务器返回 交换队员  
        ProtocolsEnum.SFriendsInfoInit = 806433; // 好友信息初始化加载   
        ProtocolsEnum.SFriendsOnline = 806434; // 好友上下线   
        ProtocolsEnum.CSendMessageToRole = 806435; // 聊天C-->S   
        ProtocolsEnum.SFriendMessageToRole = 806436; // 好友聊天聊天S-->C   
        ProtocolsEnum.SStrangerMessageToRole = 806443; //    
        ProtocolsEnum.SOffLineMsgMessageToRole = 806537; // 角色上线客户端收到   
        ProtocolsEnum.CBreakOffRelation = 806437; // 删除好友   
        ProtocolsEnum.SBreakOffRelation = 806438; // 删除好友成功   
        ProtocolsEnum.CRequestAddFriend = 806439; // 加好友C-->S   
        ProtocolsEnum.SAddFriend = 806440; // 添加好友成功S-->C   
        ProtocolsEnum.CChangeBaseConfig = 806441; // 改变基本设置C-->S   
        ProtocolsEnum.SChangeBaseConfig = 806442; // 改变基本设置S-->C   
        ProtocolsEnum.CRequestUpdateRoleInfo = 806533; // 请求陌生人的信息弹出聊天框   
        ProtocolsEnum.SRequestUpdateRoleInfo = 806534; // 弹出陌生人信息聊天框   
        ProtocolsEnum.CRequestSpaceRoleInfo = 806538; // 请求空间角色信息   
        ProtocolsEnum.SRequestSpaceRoleInfo = 806539; // 返回空间角色信息   
        ProtocolsEnum.SUpdateFriendLevel = 806536; // 服务器通知客户端刷新好友度   
        ProtocolsEnum.SSendSystemMessageToRole = 806555; // 聊天S-->C   
        ProtocolsEnum.CReqJionCamp = 806558; // 请求加入阵营   
        ProtocolsEnum.SJionCamp = 806559; // 加入阵营   
        ProtocolsEnum.CCampPK = 806562; // 阵营pk   
        ProtocolsEnum.CRequestSearchFriend = 806570; // <!-- 好友搜索相关 -->搜索好友C-->S 
        ProtocolsEnum.SSearchFriend = 806571; // 搜索好友成功S-->C   
        ProtocolsEnum.SUpdateFriendState = 806575; //    
        ProtocolsEnum.CRecommendFriend = 806576; // 客户端请求推荐好友   
        ProtocolsEnum.SRecommendFriend = 806577; //服务器返回推荐好友    
        ProtocolsEnum.CGiveInfoList = 806633; // 客户端请求好友赠送信息列表   
        ProtocolsEnum.SGiveInfoList = 806634; // <!-- 服务器返回好友赠送信息列表 --> 
        ProtocolsEnum.CGiveItem = 806635; // <!-- 赠送道具 --> 
        ProtocolsEnum.SGiveItem = 806636; // <!-- 赠送道具结果 --> 
        ProtocolsEnum.CGiveGift = 806637; //    
        ProtocolsEnum.SGiveGift = 806638; //    
        ProtocolsEnum.CGetSpaceInfo = 806639; //    
        ProtocolsEnum.SGetSpaceInfo = 806640; // 获取某角色空间数据结果   
        ProtocolsEnum.CSetSpaceGift = 806641; // 放置角色空间礼物   
        ProtocolsEnum.SSetSpaceGift = 806642; // 放置角色空间礼物结果   
        ProtocolsEnum.CStepSpace = 806643; // 踩某个角色空间   
        ProtocolsEnum.SStepSpace = 806644; // 踩某个角色空间结果   
        ProtocolsEnum.CGetRolesLevel = 806645; // 获取一批角色等级   
        ProtocolsEnum.SGetRolesLevel = 806646; // 返回一批角色等级   
        ProtocolsEnum.CXshSpace = 806647; // 踩说不得大师空间   
        ProtocolsEnum.SXshSpace = 806648; // 踩说不得大师空间结果   
        ProtocolsEnum.CXshGiveGift = 806649; // 赠送说不得大师礼物   
        ProtocolsEnum.SXshGiveGift = 806650; // 赠送说不得大师礼物结果   
        ProtocolsEnum.CGetXshSpaceInfo = 806651; // 获取说不得大师空间数据   
        ProtocolsEnum.SGetXshSpaceInfo = 806652; // 获取说不得大师空间数据结果   
        ProtocolsEnum.CGetRecruitAward = 806662; // <!-- 招募 --> 
        ProtocolsEnum.SGetRecruitAward = 806663; //    
        ProtocolsEnum.CReqRecruitWheel = 806664; // 请求招募大转盘信息   
        ProtocolsEnum.SReqRecruitWheel = 806665; // 请求招募大转盘信息结果   
        ProtocolsEnum.CBeginRecruitWheel = 806666; // 开始转招募大转盘   
        ProtocolsEnum.SBeginRecruitWheel = 806667; // 开始转招募大转盘结果   
        ProtocolsEnum.SSignList = 806683; // 签名列表 key=角色id value=签名内容 
        ProtocolsEnum.CSetSign = 806684; // 设置签名   
        ProtocolsEnum.CRequestMarry = 806693; // 申请结婚(队长)   
        ProtocolsEnum.SRequestMarry = 806694; // 申请结婚结果(广播给队员)   
        ProtocolsEnum.CRespondMarry = 806695; // 响应结婚申请(队员)   
        ProtocolsEnum.SRespondMarry = 806696; // 响应结婚申请结果(广播给队员)   
        ProtocolsEnum.CGetMarriageInfo = 806697; // 请求玩家婚姻信息   
        ProtocolsEnum.SGetMarriageInfo = 806698; // 返还玩家婚姻信息   
        ProtocolsEnum.CGetMarriageAnniversaryAward = 806699; // 领取结婚周年礼盒   
        ProtocolsEnum.CRequestWedding = 806703; // <!-- 婚宴协议 20271-20290--> 
        ProtocolsEnum.SRequestWedding = 806704; // 申请举办婚宴结果   
        ProtocolsEnum.CInviteFriends = 806705; // 邀请好友来婚宴   
        ProtocolsEnum.SInviteFriend = 806706; // 通知被邀请的好友   
        ProtocolsEnum.SWeddingBegin = 806710; // 婚宴开始(广播婚宴地图所有玩家)   
        ProtocolsEnum.CRespondWeddingInvite = 806707; // 好友响应邀请   
        ProtocolsEnum.SRespondWeddingInvite = 806713; // 好友响应邀请结果   
        ProtocolsEnum.CGiveAsPresent = 806708; // 赠送新人礼物   
        ProtocolsEnum.SGiveAsPresent = 806709; // 赠送新人礼物结果   
        ProtocolsEnum.CBeginWeddingRoll = 806711; // 请求婚礼roll点开始   
        ProtocolsEnum.SBeginWeddingRoll = 806712; // 婚礼roll点开始(广播所有参加婚礼的玩家)   
        ProtocolsEnum.CWeddingRoll = 806714; // 玩家点击roll点   
        ProtocolsEnum.SWeddingEnd = 806715; // 婚宴结束(广播所有参加婚礼的玩家)   
        ProtocolsEnum.CRequestForcibleDivorce = 806723; // 申请强制离婚<!-- 离婚协议 20291-20310--> 
        ProtocolsEnum.SRequestForcibleDivorce = 806724; // 申请强制离婚结果   
        ProtocolsEnum.CRefuseForcibleDivorce = 806725; // 拒绝强制离婚   
        ProtocolsEnum.SRefuseForcibleDivorce = 806726; // 拒绝强制离婚结果   
        ProtocolsEnum.CCancelForcibleDivorce = 806733; // 取消强制离婚   
        ProtocolsEnum.SCancelForcibleDivorce = 806734; // 确取消强制离婚结果   
        ProtocolsEnum.CConfirmForcibleDivorce = 806727; // 确认强制离婚   
        ProtocolsEnum.SConfirmForcibleDivorce = 806728; // 确认强制离婚结果   
        ProtocolsEnum.CRequestPeacefulDivorce = 806729; // 申请协议离婚   
        ProtocolsEnum.SRequestPeacefulDivorce = 806730; // 申请协议离婚结果   
        ProtocolsEnum.CRespondPeacefulDivorce = 806731; // 响应协议离婚申请   
        ProtocolsEnum.SRespondPeacefulDivorce = 806732; // 响应协议离婚申请结果   
        ProtocolsEnum.CGetMarriageSkillInfo = 806743; // 请求婚姻技能信息   
        ProtocolsEnum.SGetMarriageSkillInfo = 806744; // 响应请求婚姻技能信息   
        ProtocolsEnum.CStudyMarriageSkill = 806745; // 请求学习婚姻技能   
        ProtocolsEnum.SStudyMarriageSkill = 806746; // 请求学习婚姻技能结果   
        ProtocolsEnum.SRefreshMarriageMission = 806763; // <!-- 结婚任务协议 20331-20350--> 
        ProtocolsEnum.SReqFushiNum = 812442; // 通知客户端刷新符石的数量   
        ProtocolsEnum.CReqCharge = 812454; // 客户端要充值,服务器返回SReqCharge   
        ProtocolsEnum.SReqCharge = 812455; // 符石商品的列表   
        ProtocolsEnum.CConfirmCharge = 812456; // 客户端点购买按钮确认充值   
        ProtocolsEnum.SConfirmCharge = 812457; //    
        ProtocolsEnum.SRefreshChargeState = 812461; // 服务器同步充值状态   
        ProtocolsEnum.CGetFirstPayReward = 812462; // 领取首充奖励   
        ProtocolsEnum.CReqServerId = 812472; // 请求服务器id   
        ProtocolsEnum.SRspServerId = 812473; //    
        ProtocolsEnum.CRequestChargeReturnProfit = 812479; //    
        ProtocolsEnum.SRequestChargeReturnProfit = 812480; // 返回充值返利数据   
        ProtocolsEnum.CGrabChargeReturnProfitReward = 812481; // 领取充值返利奖励   
        ProtocolsEnum.SGrabChargeReturnProfitReward = 812482; // 领取结果 by changhao 
        ProtocolsEnum.CReqChargeRefundsInfo = 812483; // 请求封测充值返还数据   
        ProtocolsEnum.SReqChargeRefundsInfo = 812484; // 返回封测充值返还数据   
        ProtocolsEnum.CGetChargeRefunds = 812485; // 领取封测充值返还数据   
        ProtocolsEnum.SGetChargeRefunds = 812486; // 领取封测充值返还数据结果   
        ProtocolsEnum.CRequestVipInfo = 812487; //    
        ProtocolsEnum.CRequestVipJiangli = 812488; // 那个等级的奖励   
        ProtocolsEnum.SSendVipInfo = 812489; //    
        ProtocolsEnum.CReqFushiInfo = 812490; //    
        ProtocolsEnum.SReqFushiInfo = 812491; //    
        ProtocolsEnum.CUpYingYongBaoInfo = 812492; //    
        ProtocolsEnum.CSendRedPackView = 812532; // 红包界面   
        ProtocolsEnum.SSendRedPackView = 812533; // 返回红包界面   
        ProtocolsEnum.CSendRedPack = 812534; // 发送红包   
        ProtocolsEnum.SSendRedPack = 812535; // 发送红包成功返回   
        ProtocolsEnum.CGetRedPack = 812536; // 领取红包   
        ProtocolsEnum.SGetRedPack = 812537; // 返回领取红包   
        ProtocolsEnum.CSendRedPackHisView = 812538; // 查看红包历史   
        ProtocolsEnum.SSendRedPackHisView = 812539; // 返回红包历史   
        ProtocolsEnum.CSendRedPackRoleRecordView = 812540; // 查看玩家红包记录   
        ProtocolsEnum.SSendRedPackRoleRecordView = 812541; // 查看玩家红包记录   
        ProtocolsEnum.SNoticeRedPack = 812542; // 推送红包信息   
        ProtocolsEnum.SNoticeRedPackList = 812543; // 上线推送红包信息   
        ProtocolsEnum.SPayServerType = 812592; //    
        ProtocolsEnum.SHaveDayPay = 812593; // 是否已经消耗日卡 by changhao 
        ProtocolsEnum.SQueryConsumeDayPay = 812594; // 询问是否发送消耗点卡   
        ProtocolsEnum.CQueryConsumeDayPay = 812595; // 是否消耗点卡 by changhao 
        ProtocolsEnum.SConsumeDayPay = 812596; // 消耗点卡 by changhao 
        ProtocolsEnum.CQuerySubscribeInfo = 812597; // 查询订阅信息   
        ProtocolsEnum.SQuerySubscribeInfo = 812598; // 返回订阅信息   
        ProtocolsEnum.CBuySpotCard = 812633; // 求购符石   
        ProtocolsEnum.SBuySpotCard = 812634; //    
        ProtocolsEnum.CSellSpotCard = 812635; // 寄售符石   
        ProtocolsEnum.SSellSpotCard = 812636; //    
        ProtocolsEnum.CTradingSpotCardView = 812637; // 交易区界面   
        ProtocolsEnum.STradingSpotCardView = 812638; // 交易区界面   
        ProtocolsEnum.CRoleTradingView = 812639; // 个人买卖界面   
        ProtocolsEnum.SRoleTradingView = 812640; // 个人买卖界面   
        ProtocolsEnum.CRoleTradingRecordView = 812641; // 个人买卖记录界面   
        ProtocolsEnum.SRoleTradingRecordView = 812642; // 个人买卖记录界面   
        ProtocolsEnum.CCancelTrading = 812643; // 撤销订单   
        ProtocolsEnum.SCancelTrading = 812644; // 撤销订单   
        ProtocolsEnum.CTradingOpenState = 812645; // 交易所功能是否开启   
        ProtocolsEnum.STradingOpenState = 812646; // 交易所功能是否开启   
        ProtocolsEnum.CBuyMonthCard = 812687; // 购买月卡 by changhao 
        ProtocolsEnum.SMonthCard = 812688; // 返回月卡结束时间戳   
        ProtocolsEnum.CGrabMonthCardReward = 812689; // 领取月卡单独道具奖励   
        ProtocolsEnum.CGrabMonthCardRewardAll = 812690; // 领取月卡奖励 by changhao 
        ProtocolsEnum.CRequestMonthCard = 812691; // 请求服务器月卡信息   
        ProtocolsEnum.CBeginSchoolWheel = 810363; //    
        ProtocolsEnum.SBeginSchoolWheel = 810364; //    
        ProtocolsEnum.CEndSchoolWheel = 810365; //    
        ProtocolsEnum.CBeginXueYueWheel = 810366; // <!--血月商人-->   
        ProtocolsEnum.SBeginXueYueWheel = 810367; //    
        ProtocolsEnum.CEndXueYueWheel = 810368; //    
        ProtocolsEnum.CUseXueYueKey = 810369; //    
        ProtocolsEnum.SUseXueYueKey = 810370; //    
        ProtocolsEnum.SRoleAccusation = 810371; //<!--血月商人 end-->   
        ProtocolsEnum.CRoleAccusationCheck = 810372; // <!--举报时候客户端给服务器发消息,用于扣费-->   
        ProtocolsEnum.SRoleAccusationCheck = 810373; //    
        ProtocolsEnum.CLogPushToken = 810374; //    
        ProtocolsEnum.CNoOperationKick = 810375; // <!--踢掉长时间不操作的玩家-->   
        ProtocolsEnum.CClientTime = 810376; //    
        ProtocolsEnum.SRefreshRoleHookData = 810333; //服务器刷新挂机数据    
        ProtocolsEnum.CSetAutoBattle = 810334; //    
        ProtocolsEnum.CSetCharOpt = 810335; //    
        ProtocolsEnum.CSetPetOpt = 810336; //    
        ProtocolsEnum.CGetDPoint = 810337; // 获取双倍点数   
        ProtocolsEnum.CFreezeDPoint = 810338; //冻结双倍点数    
        ProtocolsEnum.SRefreshRoleHookBattleData = 810339; //服务器刷新挂机战斗相关数据    
        ProtocolsEnum.SRefreshRoleHookExpData = 810340; //服务器刷新挂机经验相关数据    
        ProtocolsEnum.CSetRoleFightAI = 810341; // 设置人物战斗ai   
        ProtocolsEnum.CGetRoleFightAI = 810342; // 获取人物战斗ai   
        ProtocolsEnum.SFlushRoleFightAI = 810343; //刷新人物战斗ai    
        ProtocolsEnum.CClientLockScreen = 810344; // 机器锁屏通知服务器   
        ProtocolsEnum.CBuyDPoint = 810345; // 购买双倍点数   
        ProtocolsEnum.CSendCommand = 791433; // <!-- 5001 开始 -->
        ProtocolsEnum.CGMCheckRoleID = 791434; // 请求角色ID检测   
        ProtocolsEnum.SGMCheckRoleID = 791435; // GM 检测的角色ID正确时，服务器回复 GM 角色ID检测的请求，
        ProtocolsEnum.CCheckGM = 791436; // 客户端请求，是不是GM帐号   
        ProtocolsEnum.SCheckGM = 791437; // GM帐号才回消息   
        ProtocolsEnum.SHuobanList = 818833; // <!-- huoban协议号从 32400 到32500
        ProtocolsEnum.CGetHuobanDetailInfo = 818834; //    
        ProtocolsEnum.SHuobanDetail = 818835; //    
        ProtocolsEnum.SZhenrongInfo = 818836; //    
        ProtocolsEnum.CSwitchZhenrong = 818837; //    
        ProtocolsEnum.CZhenrongMember = 818838; //    
        ProtocolsEnum.SChangeZhenrong = 818839; //    
        ProtocolsEnum.CActiveHuoBan = 818840; // 解锁伙伴请求   
        ProtocolsEnum.SActiveHuoBan = 818841; // 解锁伙伴返回   
        ProtocolsEnum.CSwitchZhenfa = 818842; // 改变阵容的光环   
        ProtocolsEnum.SSwitchZhenfa = 818843; // 改变阵容的光环返回   
        ProtocolsEnum.CGetHuoBanList = 818844; // 获取伙伴信息列表   
        ProtocolsEnum.SGongHuiFuBenLastTime = 804533; // 公会副本剩余时间   
        ProtocolsEnum.SBingFengLandInfo = 804552; // 每个冰封王座副本的信息,冰封王座的排行榜通过SRequestRankList发送给客户端,本人的排名也在SRequestRankList中   
        ProtocolsEnum.CEnterBingFengLand = 804553; // 请求进入冰封王座副本   
        ProtocolsEnum.CLeaveBingFengLand = 804558; // 请求离开冰封王座副本   
        ProtocolsEnum.SEnterBingFengLand = 804559; //玩家进入冰封王座地图的时候,会发这条消息,客户端根据这条协议可以决定显示哪些npc和挑战的关数    
        ProtocolsEnum.CReqBingFengRank = 804556; // 客户端请求打开冰封王座的界面   
        ProtocolsEnum.CCanEnterBingFeng = 804557; // 玩家能够进入冰封王座   
        ProtocolsEnum.SCanEnterBingFeng = 804562; // 玩家能够进入冰封王座   
        ProtocolsEnum.CGetBingFengDetail = 804565; // 获取该关卡最快通关信息   
        ProtocolsEnum.SGetBingFengDetail = 804566; // 关卡最快通关信息   
        ProtocolsEnum.CBattletoBingFeng = 804567; // 机器人发送战斗信息   
        ProtocolsEnum.SItemNumChange = 787434; //    
        ProtocolsEnum.SItemPosChange = 787441; //    
        ProtocolsEnum.SDelItem = 787435; //    
        ProtocolsEnum.SAddItem = 787436; //    
        ProtocolsEnum.SRefreshItemFlag = 787437; //    
        ProtocolsEnum.SRefreshItemTimeout = 787438; //    
        ProtocolsEnum.CItemLoseEffect = 787439; //    
        ProtocolsEnum.CGetPackInfo = 787442; //    
        ProtocolsEnum.SGetPackInfo = 787443; //    
        ProtocolsEnum.CListPack = 787444; //    
        ProtocolsEnum.CPutOnEquip = 787445; //    
        ProtocolsEnum.CTakeOffEquip = 787446; //    
        ProtocolsEnum.CTransItem = 787447; //    
        ProtocolsEnum.CDropItem = 787449; //    
        ProtocolsEnum.SRefreshCurrency = 787450; //    
        ProtocolsEnum.CPutOnPetEquip = 787451; //    
        ProtocolsEnum.CTakeOffPetEquip = 787452; //    
        ProtocolsEnum.CGetItemTips = 787453; //    
        ProtocolsEnum.SGetItemTips = 787454; //    
        ProtocolsEnum.CAppendItem = 787455; //    
        ProtocolsEnum.CGetPetEquipTips = 787456; //    
        ProtocolsEnum.SGetPetEquipTips = 787457; //    
        ProtocolsEnum.SRefreshPackSize = 787459; //    
        ProtocolsEnum.CCleanTempPack = 787472; //    
        ProtocolsEnum.SCleanTempPack = 787473; //    
        ProtocolsEnum.SRefreshNaiJiu = 787474; //    
        ProtocolsEnum.CXiuLiEquipItem = 787475; //    
        ProtocolsEnum.SRefreshMaxNaiJiu = 787476; //    
        ProtocolsEnum.SXiuLiFailTimes = 787477; //    
        ProtocolsEnum.CGetRoleEquip = 787478; //    
        ProtocolsEnum.SGetRoleEquip = 787479; //    
        ProtocolsEnum.CGetRolePetInfo = 787482; //    
        ProtocolsEnum.SPetEquipAddItem = 787483; //    
        ProtocolsEnum.SPetEquipDelItem = 787484; //    
        ProtocolsEnum.SItemSign = 787486; //    
        ProtocolsEnum.CAttachGem = 787493; //    
        ProtocolsEnum.SHeChengRet = 787488; //    
        ProtocolsEnum.SAllEquipScore = 787505; //    
        ProtocolsEnum.CGetTimeAward = 787506; //    
        ProtocolsEnum.SGetTimeAward = 787507; //    
        ProtocolsEnum.CGetEquipTips = 787652; //    
        ProtocolsEnum.SGetEquipTips = 787653; //    
        ProtocolsEnum.CReqAllNaiJiu = 787654; //    
        ProtocolsEnum.COpenItemBag = 787655; //打开道具背包 by changhao  
        ProtocolsEnum.SItemAdded = 787658; //    
        ProtocolsEnum.CHeChengItem = 787689; //    
        ProtocolsEnum.SHeChengItem = 787690; //    
        ProtocolsEnum.CHeChengPetEquip = 787691; //    
        ProtocolsEnum.SHeChengPetEquip = 787692; //    
        ProtocolsEnum.SMailList = 787700; // 通知客户端邮件列表   
        ProtocolsEnum.CMailRead = 787701; // 客户端申请设置邮件已读   
        ProtocolsEnum.CMailGetAward = 787704; // 客户端申请获取邮件奖励   
        ProtocolsEnum.SMailInfo = 787705; // 通知客户端刷新邮件   
        ProtocolsEnum.SMailState = 787706; //通知客户端刷新邮件状态    
        ProtocolsEnum.CDelGem = 787702; //    
        ProtocolsEnum.CGetRoleInfo = 787709; //    
        ProtocolsEnum.SGetRoleInfo = 787710; //    
        ProtocolsEnum.SNoticeRoleGetInfo = 787711; //    
        ProtocolsEnum.SMulDayLogin = 787731; //    
        ProtocolsEnum.CGetMulDayLoginGift = 787732; //    
        ProtocolsEnum.CExtPackSize = 787737; //    
        ProtocolsEnum.COpenPack = 787738; //    
        ProtocolsEnum.SOpenPack = 787739; //    
        ProtocolsEnum.CBuyPackMoney = 787746; //    
        ProtocolsEnum.SBuyPackMoney = 787747; //    
        ProtocolsEnum.SFreshRepairData = 787756; // 刷新修理物品界面数据   
        ProtocolsEnum.CReplaceGemFromEquip = 787759; // 客户端申请替换宝石   
        ProtocolsEnum.COneKeyMoveTempToBag = 787760; // 一键把物品从临时背包移动到背包   
        ProtocolsEnum.SRepairResult = 787761; //修理结果    
        ProtocolsEnum.CListDepot = 787762; //    
        ProtocolsEnum.SUseEnhancementItem = 787764; //    
        ProtocolsEnum.SReplaceGem = 787765; // 宝石替换   
        ProtocolsEnum.CReplaceGem = 787766; // 宝石替换   
        ProtocolsEnum.COtherItemTips = 787767; // 摆摊Tip请求   
        ProtocolsEnum.SOtherItemTips = 787768; // 摆摊Tip返回   
        ProtocolsEnum.CGetDepotInfo = 787769; //    
        ProtocolsEnum.SGetDepotInfo = 787770; //    
        ProtocolsEnum.CModifyDepotName = 787771; //修改仓库名称    
        ProtocolsEnum.SModifyDepotName = 787772; //修改仓库名称返回    
        ProtocolsEnum.SRideUpdate = 787783; // 合成宝石   
        ProtocolsEnum.CComposeGem = 787784; // 合成宝石   
        ProtocolsEnum.CItemRecoverList = 787793; // 客户端请求道具找回列表   
        ProtocolsEnum.SItemRecoverList = 787794; // 服务器返回道具找回列表   
        ProtocolsEnum.CItemRecover = 787795; // 客户端请求道具找回   
        ProtocolsEnum.SItemRecover = 787796; // 服务器返回道具找回结果   
        ProtocolsEnum.CRecoverItemInfo = 787797; // 客户端请求查看一个找回道具的信息   
        ProtocolsEnum.SRecoverItemInfo = 787798; // 服务器返回一个找回道具的信息   
        ProtocolsEnum.CRefineEquipBase = 787803; // 洗基础属性   
        ProtocolsEnum.SRefineEquipBase = 787804; //    
        ProtocolsEnum.CSaveRefineData = 787805; // 保存基础属性   
        ProtocolsEnum.CRefineEquipSkill = 787806; // 洗特技   
        ProtocolsEnum.CRefineEquipAll = 787807; // 洗所有属性   
        ProtocolsEnum.SRefineEquipResult = 787808; //    
        ProtocolsEnum.SExpFactorEffect = 787809; // 洗所有属性   
        ProtocolsEnum.CReqLockInfo = 818933; // 客户端请求角色安全锁信息   
        ProtocolsEnum.CReqAddLock = 818934; // 客户端请求设置安全锁   
        ProtocolsEnum.CReqUnlock = 818935; // 客户端请求解锁   
        ProtocolsEnum.CReqForceUnlock = 818936; // 客户端请求强行解锁   
        ProtocolsEnum.CReqChangePassword = 818937; // 客户端请求修改密码   
        ProtocolsEnum.CReqCancelLock = 818938; // 客户端请求取消安全锁   
        ProtocolsEnum.SLockInfo = 818939; // 服务器返回角色安全锁信息   
        ProtocolsEnum.SNeedUnlock = 818940; // 服务器通知客户端需要解锁   
        ProtocolsEnum.SAddLockSuc = 818941; // 服务器通知客户端设置安全锁成功   
        ProtocolsEnum.SUnlockSuc = 818942; // 服务器通知客户端解锁成功   
        ProtocolsEnum.SCancelLockSuc = 818943; // 服务器通知客户端取消安全锁成功   
        ProtocolsEnum.SForceUnlockSuc = 818944; // 服务器通知客户端申请强行解锁成功   
        ProtocolsEnum.SChangePasswordSuc = 818945; // 服务器通知客户端修改密码成功   
        ProtocolsEnum.SUpdateLockInfo = 818946; // 服务器返回更新的角色安全锁信息   
        ProtocolsEnum.SRegMaster = 816433; //    
        ProtocolsEnum.SReadyRegMaster = 816434; // 返回一页师傅列表   
        ProtocolsEnum.CRegMaster = 816435; // 注册为师傅   
        ProtocolsEnum.CSearchMaster = 816437; // 查找师傅   
        ProtocolsEnum.SSearchMaster = 816438; // 查找师傅   
        ProtocolsEnum.CRequestAsApprentice = 816439; // 请求师傅的id   
        ProtocolsEnum.SRequestAsApprentice = 816440; // 是否接受徒弟的确认框   
        ProtocolsEnum.CPrenticeRequestResult = 816441; //    
        ProtocolsEnum.SRequestPrenticeSuccess = 816442; //    
        ProtocolsEnum.CCanAcceptPrentice = 816443; //    
        ProtocolsEnum.SCanAcceptPrentice = 816444; //    
        ProtocolsEnum.CConfirmRegMaster = 816445; // 确定登记做师父   
        ProtocolsEnum.CSearchPrentice = 816446; // 查找徒弟   
        ProtocolsEnum.SSearchPrentice = 816447; // 寻找徒弟   
        ProtocolsEnum.SMasterPrenticeData = 816448; //    
        ProtocolsEnum.CDissolveRelation = 816449; //    
        ProtocolsEnum.SDissolveRelation = 816450; //    
        ProtocolsEnum.SPreviousMasters = 816451; //    
        ProtocolsEnum.CSelectedMasterAward = 816452; //    
        ProtocolsEnum.SPrenticeList = 816453; //    
        ProtocolsEnum.CSelectedPrenticePassBook = 816454; //    
        ProtocolsEnum.CEvaluateMasterResult = 816456; //    
        ProtocolsEnum.SReceiveNewPrentice = 816457; //    
        ProtocolsEnum.CRequestAsMaster = 816458; //    
        ProtocolsEnum.SRequestAsMaster = 816459; //    
        ProtocolsEnum.CMasterRequestResult = 816460; //    
        ProtocolsEnum.SInitPrenticeList = 816461; //    
        ProtocolsEnum.SCanRequestAsPrentice = 816462; //    
        ProtocolsEnum.CSendRequestWordToMaster = 816463; //    
        ProtocolsEnum.SCanRequestAsMaster = 816464; //    
        ProtocolsEnum.CSendRequestWordToPrentice = 816465; //    
        ProtocolsEnum.SCantRequestAsPrentice = 816466; //    
        ProtocolsEnum.SCantRequestAsMaster = 816467; //    
        ProtocolsEnum.CRequestMasterPrenticeList = 816468; //    
        ProtocolsEnum.SSendMasterPrenticeList = 816469; //    
        ProtocolsEnum.SAddPrePrentice = 816470; //    
        ProtocolsEnum.CRequestPrenticeOnLineState = 816471; //    
        ProtocolsEnum.SSendPrenticeOnLineState = 816472; //    
        ProtocolsEnum.CRequestGiveMasterPrenticeTips = 816473; //    
        ProtocolsEnum.SNotifyMaster = 816436; //    
        ProtocolsEnum.SEvaluate = 816474; //    
        ProtocolsEnum.CEvaluate = 816475; //    
        ProtocolsEnum.SDismissApprentces = 816476; //    
        ProtocolsEnum.CDismissApprentce = 816477; //    
        ProtocolsEnum.SNotifyDismissMaster = 816478; //    
        ProtocolsEnum.CDismissMaster = 816479; //    
        ProtocolsEnum.CReqApprences = 816480; //    
        ProtocolsEnum.SPrenticesList = 816481; //    
        ProtocolsEnum.CTakeAchiveAward = 816482; //    
        ProtocolsEnum.STakeAchiveFresh = 816483; //    
        ProtocolsEnum.SNotifyAppMaster = 816484; //    
        ProtocolsEnum.CAppMaster = 816485; //    
        ProtocolsEnum.CCommitMission = 805444; //    
        ProtocolsEnum.SAcceptMission = 805445; //    
        ProtocolsEnum.SRefreshMissionState = 805447; //    
        ProtocolsEnum.CAnswerQuestion = 805448; //    
        ProtocolsEnum.SRefreshMissionValue = 805449; // 任务id   
        ProtocolsEnum.CTrackMission = 805450; //    
        ProtocolsEnum.STrackMission = 805451; //    
        ProtocolsEnum.CActiveMissionAIBattle = 805452; // 激活任务AI战斗服务   
        ProtocolsEnum.SFairylandStatus = 805453; //    
        ProtocolsEnum.CAbsentFairyland = 805454; //    
        ProtocolsEnum.CReturnFairyland = 805455; //    
        ProtocolsEnum.CReqMissionCanAccept = 805456; //    
        ProtocolsEnum.SReqMissionCanAccept = 805457; //    
        ProtocolsEnum.CMissionDialogEnd = 805458; // 任务对话结束   
        ProtocolsEnum.SUseMissionItemFail = 805459; // 使用任务物品结束   
        ProtocolsEnum.CMissionReachScene = 805460; // 跳转地图   
        ProtocolsEnum.STrackedMissions = 805461; //    
        ProtocolsEnum.SNpcFollowStart = 805501; //    
        ProtocolsEnum.SNpcFollowEnd = 805502; //    
        ProtocolsEnum.CReqLandTask = 805468; // 客户端请求获得副本任务   
        ProtocolsEnum.CAskLandTimes = 805469; // 客户端请求获得副本任务次数   
        ProtocolsEnum.SLandTimes = 805470; //    
        ProtocolsEnum.SCopyDestroyTime = 805471; //    
        ProtocolsEnum.CGetInstanceState = 805472; //    
        ProtocolsEnum.SGetInstanceState = 805473; //    
        ProtocolsEnum.CGetLineState = 805474; //    
        ProtocolsEnum.SGetLineState = 805475; //    
        ProtocolsEnum.CReqLineTask = 805476; //    
        ProtocolsEnum.CNotifyTeamMemeberSubmitItem = 805477; // 时光之穴副本   
        ProtocolsEnum.CRefreshActivityListFinishTimes = 805484; // <!--新版活动日历 -->  
        ProtocolsEnum.SRefreshActivityListFinishTimes = 805485; //    
        ProtocolsEnum.CDrawGiftBox = 805488; // 领取宝箱   
        ProtocolsEnum.SDrawGiftBox = 805487; // 回复已经取过宝箱   
        ProtocolsEnum.SActivityOpen = 805486; // 有活动开启   
        ProtocolsEnum.CShareActivity = 805489; // 分享活动专用！   
        ProtocolsEnum.CReqGoto = 805516; //    
        ProtocolsEnum.SNotifyTuiSongList = 805518; //    
        ProtocolsEnum.CReqJionActivity = 805517; //    
        ProtocolsEnum.SDailyTaskStateList = 805520; // 推送日常任务状态   
        ProtocolsEnum.SRemoveTuiSong = 805521; //    
        ProtocolsEnum.SQuestion = 805527; //    
        ProtocolsEnum.CAnsQuestion = 805528; //    
        ProtocolsEnum.CUseTreasureMap = 805532; //    
        ProtocolsEnum.SUseTreasureMap = 805533; //    
        ProtocolsEnum.CUseTreasureMapEnd = 805534; //    
        ProtocolsEnum.CGetActivityInfo = 805536; //    
        ProtocolsEnum.SGetActivityInfo = 805537; //    
        ProtocolsEnum.SAskIntoInstance = 805538; //    
        ProtocolsEnum.CAskIntoInstance = 805539; //    
        ProtocolsEnum.CGetArchiveInfo = 805540; //    
        ProtocolsEnum.SGetArchiveInfo = 805541; //    
        ProtocolsEnum.CGetArchiveAward = 805542; //    
        ProtocolsEnum.SWaitRollTime = 805543; //    
        ProtocolsEnum.SPlayXianJingCG = 805544; //    
        ProtocolsEnum.SAddTreasureMap = 805545; //    
        ProtocolsEnum.SAnswerInstance = 805546; //    
        ProtocolsEnum.SDefineTeam = 805547; //    
        ProtocolsEnum.CDefineTeam = 805548; //    
        ProtocolsEnum.SDropInstance = 805549; //    
        ProtocolsEnum.CDropInstance = 805550; //    
        ProtocolsEnum.CRequestChapterInfo = 805632; // <!--前尘旧梦章节战斗-->请求章节挑战数据   
        ProtocolsEnum.SRequestChapterInfo = 805633; // 返回章节挑战数据   
        ProtocolsEnum.CRequestChapterChallenge = 805634; // 申请章节挑战(队长)   
        ProtocolsEnum.SRequestChapterChallenge = 805635; // 返回申请章节挑战结果   
        ProtocolsEnum.CRespondChapterChallenge = 805636; // 响应队长申请章节挑战请求   
        ProtocolsEnum.CRoleMove = 790433; // 角色请求移动   
        ProtocolsEnum.SRoleMove = 790434; //    
        ProtocolsEnum.CCheckMove = 790435; //    
        ProtocolsEnum.SSetRoleLocation = 790436; // 服务器强制设置角色的位置   
        ProtocolsEnum.SAddUserScreen = 790437; //    
        ProtocolsEnum.SRemoveUserScreen = 790438; //    
        ProtocolsEnum.CSendAutoMovePathID = 790492; //    
        ProtocolsEnum.CRoleTurn = 790439; //    
        ProtocolsEnum.SRoleTurn = 790440; //    
        ProtocolsEnum.SRoleEnterScene = 790441; //    
        ProtocolsEnum.CRoleStop = 790442; //    
        ProtocolsEnum.SRoleStop = 790443; //    
        ProtocolsEnum.SSetRoleTeamInfo = 790444; // 设置场景中玩家的队伍信息   
        ProtocolsEnum.SAddPickupScreen = 790445; //    
        ProtocolsEnum.SRemovePickupScreen = 790446; //    
        ProtocolsEnum.CRelocateRolePos = 790447; // 玩家暂离或离开队伍时，重新告诉服务器当前坐标（逻辑坐标）   
        ProtocolsEnum.SHideRole = 790458; // 场景中人物进出战斗群发九屏幕   
        ProtocolsEnum.SRelocateRolePos = 790459; // 玩家暂离或离开队伍时，服务器获取当前坐标（逻辑坐标）   
        ProtocolsEnum.SAddActivityNpc = 790463; //    
        ProtocolsEnum.SRemoveActivityNpc = 790464; //    
        ProtocolsEnum.STransfromShape = 790465; //    
        ProtocolsEnum.CEnterDangerConfirm = 790468; //    
        ProtocolsEnum.CGMGetAroundRoles = 790469; //    
        ProtocolsEnum.SGMGetAroundRoles = 790470; //    
        ProtocolsEnum.SUpdateRoleSceneState = 790471; //    
        ProtocolsEnum.SUpdateNpcSceneState = 790472; // <!-- 服务器刷新一个Npc的场景状态 --> 
        ProtocolsEnum.SRoleModelChange = 790474; //    
        ProtocolsEnum.SRoleComponentsChange = 790476; //    
        ProtocolsEnum.CRoleJump = 790477; // 角色请求跳跃   
        ProtocolsEnum.SRoleJump = 790478; // 服务器广播角色跳跃   
        ProtocolsEnum.CRoleJumpStop = 790479; // 角色跳跃停止   
        ProtocolsEnum.SRoleJumpDrawback = 790480; // 角色跳跃被拉回   
        ProtocolsEnum.SNPCMoveTo = 790482; // NPC 移动  
        ProtocolsEnum.SBeginBaitang = 790483; //    
        ProtocolsEnum.SRoleChangeShape = 790484; //    
        ProtocolsEnum.CReqSeeEachOther = 790486; //    
        ProtocolsEnum.SRolePlayAction = 790488; // 服务器广播角色做某个动作   
        ProtocolsEnum.SChangeEquipEffect = 790491; // 改变玩家装备特效   
        ProtocolsEnum.CVisitNpc = 795433; // 客户端请求访问 NPC  
        ProtocolsEnum.SVisitNpc = 795434; //    
        ProtocolsEnum.CNpcService = 795435; // 通用向服务器发送NPC服务消息（不带参数）   
        ProtocolsEnum.CReqQuestion = 795439; // 向NPC请求问题   
        ProtocolsEnum.SReqFortuneWheel = 795445; // 服务器发送抽奖   
        ProtocolsEnum.CFinishFortuneWheel = 795446; // 客户端请求领奖   
        ProtocolsEnum.SBattleToNpcError = 795453; //    
        ProtocolsEnum.SSendNpcMsg = 795454; // 服务器发送给客户端，npc提示信息   
        ProtocolsEnum.SSubmit2Npc = 795455; // 通知客户端提交任务物品或者任务宠物   
        ProtocolsEnum.CSubmit2Npc = 795456; // 客户端请求提交任务物品或者任务宠物   
        ProtocolsEnum.CDoneFortuneWheel = 795457; // 玩家完成转盘,发给玩家奖励   
        ProtocolsEnum.SAttendImpExam = 795458; // 进入游戏的时候发起的确认框   
        ProtocolsEnum.CConfirmImpExam = 795459; //    
        ProtocolsEnum.CApplyImpExam = 795460; // 申请参加智慧试炼   
        ProtocolsEnum.SSendImpExamVill = 795461; //    
        ProtocolsEnum.SSendImpExamProv = 795462; //    
        ProtocolsEnum.SSendImpExamState = 795463; //    
        ProtocolsEnum.CSendImpExamAnswer = 795464; // 智慧试炼答题请求
        ProtocolsEnum.SSendImpExamStart = 795465; //    
        ProtocolsEnum.SSendImpExamAssist = 795466; //    
        ProtocolsEnum.CImpExamHelp = 795467; // 智慧试炼求助   
        ProtocolsEnum.SImpExamHelp = 795468; //    
        ProtocolsEnum.CQueryImpExamState = 795469; // 查询是否可参加智慧试炼决赛   
        ProtocolsEnum.SQueryImpExamState = 795470; //    
        ProtocolsEnum.SWinnerChangeTask = 795483; // 冠军试炼同步任务   
        ProtocolsEnum.CWinnerChangeTask = 795484; // 冠军试炼同步任务   
        ProtocolsEnum.CStartFortuneWheel = 795494; // 客户端申请开始幸运大转盘   
        ProtocolsEnum.CHasFortuneWheel = 795495; // 客户端询问玩家是否有大转盘   
        ProtocolsEnum.SGeneralSummonCommand = 795505; // 服务器发送通用拉人消息   
        ProtocolsEnum.CGeneralSummonCommand = 795506; // 客户端回应拉人   
        ProtocolsEnum.SAskQuestion = 795520; // 服务器出题   
        ProtocolsEnum.CGiveUpQuestion = 795523; //    
        ProtocolsEnum.CGrabActivityReward = 795531; // 领取活动答题奖励 by changhao 
        ProtocolsEnum.CActivityAnswerQuestionHelp = 795532; //    
        ProtocolsEnum.CAnswerActivityQuestion = 795533; // 活动答题 by changhao 
        ProtocolsEnum.SGrabActivityReward = 795534; // 返回领取活动答题奖励 by changhao 
        ProtocolsEnum.SActivityAnswerQuestionHelp = 795535; // 活动答题帮助 by changhao 
        ProtocolsEnum.COpenChest = 795522; // 客户端请求打开宝箱   
        ProtocolsEnum.SVisitNpcContainChatMsg = 795526; //    
        ProtocolsEnum.CRequestActivityAnswerQuestion = 795527; //    
        ProtocolsEnum.SPingJi = 795667; // <!-- 通知客户端评级 以及获得的奖励 -->
        ProtocolsEnum.CExitCopy = 795668; //    
        ProtocolsEnum.SNpcBattleTime = 795669; // npc战斗匹配剩余时间   
        ProtocolsEnum.CAbandonMacth = 795670; // 放弃匹配   
        ProtocolsEnum.SMacthResult = 795671; // 匹配结果   
        ProtocolsEnum.SSendNpcService = 795689; //    
        ProtocolsEnum.CShowPet = 788433; // 客户端请求展示宠物   
        ProtocolsEnum.SShowPetAround = 788434; // 服务器通知周围玩家，玩家roleid展示了宠物pet   
        ProtocolsEnum.CShowPetOff = 788435; // 客户端请求收回展示的宠物   
        ProtocolsEnum.SRefreshPetInfo = 788437; // 刷新宠物数据 洗练后，刷新宠物几乎所有的属性  
        ProtocolsEnum.SRefreshPetExp = 788438; // 宠物只有当前经验改变时，服务器发送此消息   
        ProtocolsEnum.CPetAddPoint = 788439; // 客户端请求宠物加点   
        ProtocolsEnum.CSetFightPet = 788440; // 请求宠物参战   
        ProtocolsEnum.SSetFightPet = 788441; //    
        ProtocolsEnum.CSetFightPetRest = 788442; // 请求将参战宠物置位休息状态   
        ProtocolsEnum.SSetFightPetRest = 788443; // 收回参战宠物, 将当前的参战宠物设置为休息状态。  
        ProtocolsEnum.SAddPetToColumn = 788444; // 通知客户端添加宠物   
        ProtocolsEnum.SRemovePetFromCol = 788445; // 通知客户端删除指定宠物栏上的指定key对应的宠物   
        ProtocolsEnum.CGetPetcolumnInfo = 788446; // 客户端请求宠物栏信息   
        ProtocolsEnum.SGetPetcolumnInfo = 788447; // 服务器发送给客户端 宠物栏信息  
        ProtocolsEnum.CMovePetColumn = 788448; // 客户端请求，在宠物栏(角色宠物栏，仓库宠物栏)之间移动宠物,即存取宠物 功能  
        ProtocolsEnum.SPetError = 788449; // 宠物相关操作出错   
        ProtocolsEnum.CModPetName = 788450; // 客户端请求修改宠物名字   
        ProtocolsEnum.SModPetName = 788451; // 服务器通知客户端修改宠物的名字   
        ProtocolsEnum.SPetGossip = 788453; // 战斗内宠物闲话   
        ProtocolsEnum.SRefreshPetSkill = 788454; //    
        ProtocolsEnum.CShowPetInfo = 788456; // 客户端请求查看场景中的宠物信息   
        ProtocolsEnum.SShowPetInfo = 788457; // 服务器返回给客户端场景中某只宠物的详细信息   
        ProtocolsEnum.SRefreshPetColumnCapacity = 788458; // 服务器向客户端刷新宠物栏的最大容量   
        ProtocolsEnum.CPetLearnSkillByBook = 788479; // 宠物打技能书   
        ProtocolsEnum.CFreePet1 = 788497; // 客户端请求放生宠物 (放生成功，服务器会返回客户端删除宠物的消息  
        ProtocolsEnum.SRefreshPetScore = 788511; // 宠物评分   
        ProtocolsEnum.CPetSetAutoAddPoint = 788512; // 客户端请求设置宠物加点方案   
        ProtocolsEnum.SPetSetAutoAddPoint = 788513; // 宠物加点方案   
        ProtocolsEnum.CPetResetPoint = 788514; // 客户端请求宠物重置加点   
        ProtocolsEnum.CPetWash = 788515; // 宠物洗练   
        ProtocolsEnum.SPetWash = 788516; // 宠物洗练   
        ProtocolsEnum.CPetSynthesize = 788517; // 客户端请求宠物合成   
        ProtocolsEnum.SPetSynthesize = 788518; // 宠物合成   
        ProtocolsEnum.CPetSkillCertification = 788519; // 客户端请求宠物技能认证   
        ProtocolsEnum.SPetSkillCertification = 788520; // 宠物技能认证   
        ProtocolsEnum.CPetAptitudeCultivate = 788521; // 客户端请求资质培养   
        ProtocolsEnum.SPetAptitudeCultivate = 788522; // 资质培养   
        ProtocolsEnum.CPetExpCultivate = 788523; // 客户端请求使用经验道具   
        ProtocolsEnum.CPetDepotColumnAddCapacity = 788524; // 客户端请求宠物仓库扩容   
        ProtocolsEnum.CGetPetInfo = 788525; // 客户端请求查看某人的宠物信息   
        ProtocolsEnum.SGetPetInfo = 788526; // 宠物信息   
        ProtocolsEnum.CPetSell = 788527; // 宠物回收   
        ProtocolsEnum.CShenShouDuiHuan = 788528; // 神兽兑换,重置,养成   
        ProtocolsEnum.CShenShouChongZhi = 788529; //    
        ProtocolsEnum.CShenShouYangCheng = 788530; //    
        ProtocolsEnum.CPetLevelReset = 788543; // 宠物等级重置   
        ProtocolsEnum.CPetRecoverList = 788583; // 客户端请求宠物找回列表   
        ProtocolsEnum.SPetRecoverList = 788584; // 服务器返回宠物找回列表   
        ProtocolsEnum.CPetRecover = 788585; // 客户端请求宠物找回   
        ProtocolsEnum.SPetRecover = 788586; // 服务器返回宠物找回结果   
        ProtocolsEnum.CRecoverPetInfo = 788587; // 客户端请求查看一个找回宠物的信息   
        ProtocolsEnum.SRecoverPetInfo = 788588; // 服务器返回一个找回宠物的信息   
        ProtocolsEnum.CReqBlackRoles = 819143; //    
        ProtocolsEnum.SBlackRoles = 819144; // 服务器返回黑名单列表信息   
        ProtocolsEnum.CSearchBlackRole = 819145; // 客户端搜索玩家   
        ProtocolsEnum.SSearchBlackRoleInfo = 819146; // 服务器返回搜索的角色信息   
        ProtocolsEnum.CRemoveBlackRole = 819147; // 客户端请求移除黑名单   
        ProtocolsEnum.CAddBlackRole = 819148; // 客户端请求屏蔽玩家(添加黑名单)   
        ProtocolsEnum.SErrorCode = 803441; // 服务器返回错误消息   
        ProtocolsEnum.SProductMadeUp = 803442; // 打造装备（炼药，烹饪）成功   
        ProtocolsEnum.CMakeEquip = 803451; // 装备打造   
        ProtocolsEnum.CResolveEquip = 803452; // 装备分解   
        ProtocolsEnum.CResolveGem = 803453; //    
        ProtocolsEnum.CRequestRankList = 810233; // 客户端向服务器某个排行榜列表   
        ProtocolsEnum.SRequestRankList = 810234; // 服务器返回给客户端的排行榜列表   
        ProtocolsEnum.CRequestRankPetData = 810240; // 请求榜单上宠物的详细信息   
        ProtocolsEnum.SSendRankPetData = 810241; // 服务器返回给客户端榜单上宠物的详细信息   
        ProtocolsEnum.CRankGetInfo = 810256; // 排行榜玩家信息查看   
        ProtocolsEnum.SRankRoleInfo = 810257; //    
        ProtocolsEnum.CRankGetPetInfo = 810258; //    
        ProtocolsEnum.SRankRoleInfo2 = 810261; //    
        ProtocolsEnum.SFactionRankInfo = 810262; //    
        ProtocolsEnum.SSendShouxiInfo = 810433; // 发送首席信息   
        ProtocolsEnum.SSendCandidates = 810434; // 发送首席候选人列表   
        ProtocolsEnum.SVoteCandidate = 810440; // 发送首席候选人列表   
        ProtocolsEnum.SMyElector = 810443; // 发送首席候选人列表   
        ProtocolsEnum.CSendElectorWords = 810435; // 客户端向服务器发送竞选词   
        ProtocolsEnum.CVoteCandidate = 810436; // 客户端返回给服务器投票对象   
        ProtocolsEnum.SCanElect = 810437; // 服务器发给客户端可以打开竞选框的消息   
        ProtocolsEnum.SShouxiShape = 810438; // 服务器发给客户端首席   
        ProtocolsEnum.CShouxiShape = 810439; // 客户端请求首席-弟子的外形   
        ProtocolsEnum.COldSchoolList = 810483; // 客户端请求旧的职业列表   
        ProtocolsEnum.SOldSchoolList = 810484; // 服务器返回旧的职业列表   
        ProtocolsEnum.CChangeSchool = 810485; // 客户端申请转职   
        ProtocolsEnum.CChangeSchoolExtInfo = 810487; // 客户端请求转职后,剩余转换武器、宝石的次数   
        ProtocolsEnum.SChangeSchoolExtInfo = 810488; // 服务器返回转职后,剩余转换武器、宝石的次数   
        ProtocolsEnum.CChangeWeapon = 810489; // 客户端申请转换武器(转职后开放)   
        ProtocolsEnum.SChangeWeapon = 810490; // 服务器返回转换武器成功(转职后开放)   
        ProtocolsEnum.CChangeGem = 810491; // 客户端申请转换宝石(转职后开放)   
        ProtocolsEnum.SChangeGem = 810492; // 服务器返回转换宝石成功(转职后开放)   
        ProtocolsEnum.CBuyMallShop = 810632; // 商城购买协议   
        ProtocolsEnum.CBuyNpcShop = 810633; // NPC购买协议   
        ProtocolsEnum.CChamberOfCommerceShop = 810634; // 商会买卖协议   
        ProtocolsEnum.CRequstShopPrice = 810635; // 请求服务器商店商品价格,只有NPCMT3买卖物品表.xlsx中,价格是否波动这列为1的时候,服务器才会返回价格   
        ProtocolsEnum.SResponseShopPrice = 810636; //    
        ProtocolsEnum.CQueryLimit = 810637; //    
        ProtocolsEnum.SQueryLimit = 810638; //    
        ProtocolsEnum.CMarketBrowse = 810639; //    
        ProtocolsEnum.SMarketBrowse = 810640; //    
        ProtocolsEnum.CMarketBuy = 810641; // 摆摊购买   
        ProtocolsEnum.SMarketBuy = 810642; //    
        ProtocolsEnum.CMarketUp = 810643; // 摆摊上架   
        ProtocolsEnum.CMarketDown = 810644; // 摆摊下架   
        ProtocolsEnum.CMarketTradeLog = 810645; // 摆摊交易记录   
        ProtocolsEnum.SMarketTradeLog = 810646; //    
        ProtocolsEnum.CMarketContainerBrowse = 810647; // 摆摊容器浏览   
        ProtocolsEnum.SMarketContainerBrowse = 810648; //    
        ProtocolsEnum.CMarketPetTips = 810649; //宠物tips    
        ProtocolsEnum.SMarketPetTips = 810650; //    
        ProtocolsEnum.CGetMarketUpPrice = 810651; // 获取摆摊上架价格   
        ProtocolsEnum.SGetMarketUpPrice = 810652; //    
        ProtocolsEnum.CExchangeCurrency = 810653; // 货币兑换   
        ProtocolsEnum.SMarketUpSucc = 810654; // 上架珍品成功   
        ProtocolsEnum.CExchangeShop = 810655; // 兑换商店协议   
        ProtocolsEnum.CReMarketUp = 810656; // 摆摊重新上架   
        ProtocolsEnum.SNotifyBuySuccess = 810657; // 用于客户端处理购买成功时通知   
        ProtocolsEnum.CAttentionGoods = 810658; // 关注或取消关注商品   
        ProtocolsEnum.SAttentionGoods = 810659; //    
        ProtocolsEnum.CMarketAttentionBrowse = 810660; // 摆摊关注浏览   
        ProtocolsEnum.CMarketSearchEquip = 810661; // 摆摊珍品装备搜索   
        ProtocolsEnum.CMarketSearchPet = 810662; // 摆摊宠物搜索   
        ProtocolsEnum.SMarketSearchResult = 810663; // 摆摊装备搜索宠物搜索返回
        ProtocolsEnum.CMarketCleanTradeLog = 810664; // 摆摊交易记录清除   
        ProtocolsEnum.CMarketItemChatShow = 810665; // 聊天发送摆摊道具协议   
        ProtocolsEnum.SMarketItemChatShow = 810666; //    
        ProtocolsEnum.STempMarketContainer = 810667; // 拍卖临时背包,合服后浏览道具   
        ProtocolsEnum.CTakeBackTempMarketContainerItem = 810668; // 拍卖临时背包,合服后取出道具请求   
        ProtocolsEnum.STakeBackTempMarketContainerItem = 810669; // 拍卖临时背包,合服后取出道具回复   
        ProtocolsEnum.CGoldOrderUpBlackMarket = 810670; // 金币订单上架   
        ProtocolsEnum.CGoldOrderDownBlackMarket = 810671; // 金币订单下架   
        ProtocolsEnum.CGoldOrderTakeOutBlackMarket = 810672; // 金币订单取出金币   
        ProtocolsEnum.CGoldOrderBrowseBlackMarket = 810673; // 金币订单浏览   
        ProtocolsEnum.SGoldOrderBrowseBlackMarket = 810674; //    
        ProtocolsEnum.SGoldOrderUpBlackMarket = 810675; // 添加新订单   
        ProtocolsEnum.SRefreshGoldOrderState = 810676; //    
        ProtocolsEnum.SGoldOrderDownBlackMarket = 810677; // 删除订单   
        ProtocolsEnum.CTransTianTiShop = 810678; // 天梯商城买卖协议   
        ProtocolsEnum.CItemOrderUpBlackMarket = 810679; //    
        ProtocolsEnum.CItemOrderDownBlackMarket = 810680; //    
        ProtocolsEnum.CItemOrderTakeOutBlackMarket = 810681; // 道具订单取出   
        ProtocolsEnum.CItemOrderBrowseBlackMarket = 810682; // 道具订单浏览   
        ProtocolsEnum.SItemOrderUpBlackMarket = 810683; // 通知道具新订单   
        ProtocolsEnum.SRefreshItemOrderState = 810684; // 更新订道具单状态   
        ProtocolsEnum.SItemOrderDownBlackMarket = 810685; // 道具订单下架   
        ProtocolsEnum.SItemOrderBrowseBlackMarket = 810686; // 道具订单浏览   
        ProtocolsEnum.SSkillError = 800436; // 职业心法   
        ProtocolsEnum.CUpdaetAssistSkillLevel = 800438; // 客户端：指定辅助技能升一级   
        ProtocolsEnum.SUpdateAssistSkill = 800439; // 服务器：更新某个辅助技能   
        ProtocolsEnum.SSendAssistSkillMaxLevels = 800440; // 服务器：发送角色公会的辅助技能等级上限   
        ProtocolsEnum.SSendSpecialSkills = 800443; //    
        ProtocolsEnum.CUpdateInborn = 800445; // 客户端：   
        ProtocolsEnum.SUpdateInborn = 800446; // 服务器：升级到XX级   
        ProtocolsEnum.SSendInborns = 800447; // 服务器：刷新所有等级   
        ProtocolsEnum.CUseSceneSkill = 800452; // 在场景使用技能   
        ProtocolsEnum.CPractiseSkill = 800460; // 客户端：修炼指定技能   
        ProtocolsEnum.SUpdateExtSkill = 800489; // 服务器：扩展技能更新   
        ProtocolsEnum.CRequestParticleSkillList = 800503; // 请求已经学习的修炼技能链表   
        ProtocolsEnum.SRequestParticleSkillList = 800504; // 返回已经学习的所有修炼技能   
        ProtocolsEnum.CRequestLearnParticleSkill = 800505; // 请求学习修炼技能每次增加一级 by changhao 
        ProtocolsEnum.SUpdateLearnParticleSkill = 800506; // 如果修炼技能等级有变化会更新 by changhao 
        ProtocolsEnum.CRequestLiveSkillList = 800513; // 请求已经学习的生活技能链表   
        ProtocolsEnum.SRequestLiveSkillList = 800514; // 返回已经学习的所有生活技能   
        ProtocolsEnum.CRequestLearnLiveSkill = 800515; // 请求学习生活技能每次增加一级   
        ProtocolsEnum.SUpdateLearnLiveSkill = 800516; // 如果技能等级有变化会更新   
        ProtocolsEnum.CLiveSkillMakeStuff = 800517; // 制作锻造，裁缝，炼金 符 by changhao
        ProtocolsEnum.SLiveSkillMakeStuff = 800518; // 制作药品返回 by changhao 
        ProtocolsEnum.CLiveSkillMakeDrug = 800519; // 制作药品 by changhao 
        ProtocolsEnum.SLiveSkillMakeDrug = 800520; // 制作药品返回 by changhao 
        ProtocolsEnum.CLiveSkillMakeFood = 800521; // 制作食物 by changhao 
        ProtocolsEnum.SLiveSkillMakeFood = 800522; // 制作药品返回 by changhao 
        ProtocolsEnum.CLiveSkillMakeFriendGift = 800523; // 制作同心结 by changhao 
        ProtocolsEnum.SLiveSkillMakeFriendGift = 800524; // 返回 by changhao 
        ProtocolsEnum.CLiveSkillMakeEnhancement = 800525; // 返回 by changhao 
        ProtocolsEnum.SLiveSkillMakeEnhancement = 800526; // 返回 by changhao 
        ProtocolsEnum.CLiveSkillMakeFarm = 800527; // 打工赚钱 by changhao 
        ProtocolsEnum.SLiveSkillMakeFarm = 800528; // 打工赚钱返回 by changhao 
        ProtocolsEnum.CRequestAttr = 800530; // 请求某些属性 by changhao 
        ProtocolsEnum.CLiveSkillMakeCard = 800531; // 客户端请求制作变身卡   
        ProtocolsEnum.SLiveSkillMakeCard = 800532; // 服务器返回制作变身卡成功   
        ProtocolsEnum.CShapeCardInfoList = 800583; // 客户端请求变身卡信息列表   
        ProtocolsEnum.SShapeCardInfoList = 800584; // 服务器返回变身卡信息列表   
        ProtocolsEnum.CAddShapeCardPoint = 800585; // 客户端请求增加变身卡点数   
        ProtocolsEnum.SAddShapeCardPoint = 800586; // 服务器返回增加变身卡点数   
        ProtocolsEnum.CUseShapeCard = 800587; // 客户端请求使用变身卡   
        ProtocolsEnum.SUseShapeCard = 800588; // 服务器返回使用变身卡   
        ProtocolsEnum.CUseRoleShape = 800589; // 客户端请求变身后仍显示原造型   
        ProtocolsEnum.SUseRoleShape = 800590; // 服务器返回变身后仍显示原造型   
        ProtocolsEnum.CTransChatMessage2Serv = 792433; //    
        ProtocolsEnum.STransChatMessage2Client = 792434; //    
        ProtocolsEnum.STransChatMessageNotify2Client = 792437; //    
        ProtocolsEnum.CChatItemTips = 792445; //    
        ProtocolsEnum.SChatItemTips = 792446; //    
        ProtocolsEnum.SExpMessageTips = 792447; // 这个是用来提示有多种加经验的情况   
        ProtocolsEnum.SChatHelpResult = 792448; // 聊天求助发送结果   
        ProtocolsEnum.CCreateTeam = 794433; // 角色请求建立队伍   
        ProtocolsEnum.SCreateTeam = 794434; // 服务器返回建立队伍   
        ProtocolsEnum.CAcceptToTeam = 787235; // 队长向服务器发送 接收或拒绝申请者  
        ProtocolsEnum.SAddTeamMember = 794436; // 服务器返回 添加队伍成员列表  
        ProtocolsEnum.SAddTeamApply = 794437; // 服务器返回 添加申请者列表  
        ProtocolsEnum.SRemoveTeamMember = 794438; // 服务器返回 删除队员  
        ProtocolsEnum.SRemoveTeamApply = 794439; // 服务器返回 删除申请者  
        ProtocolsEnum.CQuitTeam = 794440; // 退出队伍   
        ProtocolsEnum.CAbsentReturnTeam = 794441; // 暂离/回归队伍   
        ProtocolsEnum.SAbsentReturnTeam = 794531; // 请求回归队伍结果   
        ProtocolsEnum.CExpelMember = 794442; // 请离队员   
        ProtocolsEnum.CCallbackMember = 794443; // 请求召回队员   
        ProtocolsEnum.CSetTeamLeader = 794444; // 重新设置队长   
        ProtocolsEnum.SSetTeamLeader = 794445; // 服务器返回 重新设置队长  
        ProtocolsEnum.CInviteJoinTeam = 794446; // 邀请对方组队   
        ProtocolsEnum.SInviteJoinTeam = 794447; // 服务器返回 某人邀请自己入队，invitername为邀请者 by changhao
        ProtocolsEnum.CRespondInvite = 794448; // 回应邀请   
        ProtocolsEnum.CRequestJoinTeam = 794449; // 申请加入别人队伍   
        ProtocolsEnum.CSwapMember = 794452; // 请求交换队员   
        ProtocolsEnum.SSwapMember = 794453; // 服务器返回 交换队员  
        ProtocolsEnum.SAskforSetLeader = 794454; // 服务器返回 询问是否接受队长任命  
        ProtocolsEnum.CAnswerforSetLeader = 794455; // 回答是否接受队长任命   
        ProtocolsEnum.SAskforCallBack = 794456; // 服务器返回 询问是否接受队长召唤自己  
        ProtocolsEnum.CAnswerforCallBack = 794457; // 回答是否接受队长召唤自己   
        ProtocolsEnum.SUpdateMemberState = 794458; // 服务器返回 更新队员状态  
        ProtocolsEnum.SUpdateMemberLevel = 794459; // 服务器返回 更新队员等级  
        ProtocolsEnum.SUpdateMemberHPMP = 794460; // 服务器返回 更新队员当前生命值和魔法值  
        ProtocolsEnum.SUpdateMemberMaxHPMP = 794461; // 服务器返回 更新队员最大生命值和魔法值  
        ProtocolsEnum.CRequestSetTeamLevel = 794462; // 设置队伍等级限制   
        ProtocolsEnum.SSetTeamLevel = 794463; // 服务器返回队伍等级限制   
        ProtocolsEnum.SDismissTeam = 794466; // 服务器返回 解散队伍  
        ProtocolsEnum.SMemberSequence = 794467; // 服务器返回 队伍成员当前顺序  
        ProtocolsEnum.STeamError = 794468; //    
        ProtocolsEnum.SRequestJoinSucc = 794469; // 服务器返回 申请加队成功  
        ProtocolsEnum.SUpdateMemberPosition = 794471; // 服务器返回 更新队员当前地图和位置坐标（逻辑坐标）  
        ProtocolsEnum.SSendSingleCharacterList = 794472; // 服务器返回 附近未组队的玩家列表  
        ProtocolsEnum.SInviteJoinSucc = 794482; // 邀请某个玩家入队成功（只是邀请成功，对方还未同意）   
        ProtocolsEnum.SRequestSetLeaderSucc = 794483; // 请求提升某个玩家为队长成功（只是请求成功，对方还未同意）   
        ProtocolsEnum.SSetTeamState = 794484; // 设置自己队伍的状态   
        ProtocolsEnum.SUpdateTeamMemberBasic = 794485; // 更新某个队员的队伍数据   
        ProtocolsEnum.SRespondInvite = 794486; // 回应邀请   
        ProtocolsEnum.CDismissTeam = 794487; // 解散队伍消息   
        ProtocolsEnum.SUpdateTeamMemberComponent = 794488; // 更新某个队员的Components   
        ProtocolsEnum.CFInviteJoinTeam = 794493; // 邀请公会成员组队   
        ProtocolsEnum.CRequestTeamMatch = 794494; // 匹配组队 by changhao 
        ProtocolsEnum.SRequestTeamMatch = 794495; // 匹配组队 by changhao 
        ProtocolsEnum.CRequestStopTeamMatch = 794496; // 停止匹配组队 by changhao 
        ProtocolsEnum.SStopTeamMatch = 794497; // 停止匹配组队 by changhao 
        ProtocolsEnum.COneKeyTeamMatch = 794498; // 一键喊话 by changhao 
        ProtocolsEnum.CRequestSetTeamMatchInfo = 794499; //    
        ProtocolsEnum.SOneKeyTeamMatch = 794500; // 一键喊话成功了 by changhao 
        ProtocolsEnum.CRequestTeamMatchList = 794509; // 请求某个目标下队伍的链表 by changhao 
        ProtocolsEnum.SRequestTeamMatchList = 794510; // 返回队伍 by changhao 
        ProtocolsEnum.SForceInviteJointTeam = 794511; // 强制某个队伍邀请某人 by changhao 
        ProtocolsEnum.CRequestMatchInfo = 794512; // 请求队伍匹配和个人匹配数量   
        ProtocolsEnum.SRequestMatchInfo = 794513; //    
        ProtocolsEnum.CRequestHaveTeam = 794515; // 得到某人是否有队 by changhao 
        ProtocolsEnum.SRequestHaveTeam = 794516; //    
        ProtocolsEnum.COneKeyApplyTeamInfo = 794517; // 一键喊话队伍信息 by changhao 
        ProtocolsEnum.SOneKeyApplyTeamInfo = 794518; // 返回一键喊话队伍信息 by changhao 
        ProtocolsEnum.STeamRollMelon = 794522; // 告诉客户端开始ROLL点 by changhao 
        ProtocolsEnum.CTeamRollMelon = 794523; // 请求ROLL点 by changhao 
        ProtocolsEnum.STeamRollMelonInfo = 794524; // 大家ROLL了多少点 by changhao 
        ProtocolsEnum.CRequestRollItemTips = 794525; // 请求ROLL点产生的道具tips   
        ProtocolsEnum.SOneTeamRollMelonInfo = 794526; // 某玩家ROLL点返回ROLL了多少点   
        ProtocolsEnum.CRequestSetFormation = 794464; //    
        ProtocolsEnum.SSetTeamFormation = 794465; // 队伍阵型变化时发   
        ProtocolsEnum.SSetMyFormation = 794475; // 服务器返回玩家开启阵型   
        ProtocolsEnum.SFormationsMap = 794551; //    
        ProtocolsEnum.CFormationMakeBook = 794552; // 残卷合成 by changhao 
        ProtocolsEnum.CUseFormBook = 794553; // 使用光环书 by changhao 
        ProtocolsEnum.CRequestClanFightTeamList = 794557; // 请求公会战队伍数据 by changhao 
        ProtocolsEnum.SRequestClanFightTeamList = 794558; // 返回队伍数据 by changhao 
        ProtocolsEnum.CRequestClanFightRoleList = 794559; // 请求单人数据 by changhao 
        ProtocolsEnum.SRequestClanFightRoleList = 794560; // 返回单人数据 by changhao 
        ProtocolsEnum.CRequestClanFightTeamRoleNum = 794561; // 请求公会战队伍角色数量 by changhao 
        ProtocolsEnum.SRequestClanFightTeamRoleNum = 794562; // 返回公会战队伍角色数量 by changhao 
        ProtocolsEnum.SAddTitle = 798433; // 服务器通知客户端添加一个称谓   
        ProtocolsEnum.SRemoveTitle = 798434; // 服务器通知客户端删除一个称谓   
        ProtocolsEnum.COnTitle = 798435; // 客户端请求佩戴称谓   
        ProtocolsEnum.SOnTitle = 798436; // 服务器通知客户端佩戴称谓 同时发送周围的玩家  
        ProtocolsEnum.COffTitle = 798437; // 客户端请求卸下称谓   
        ProtocolsEnum.SOffTitle = 798438; // 服务器通知客户端卸下称谓   
        ProtocolsEnum.STitleErr = 798439; //     
        ProtocolsEnum.SEnterFuBen = 798440; //    
        ProtocolsEnum.CNpcToTrigger = 817932; // 客户端请求npc触发   
        return ProtocolsEnum;
    }());
    hanlder.ProtocolsEnum = ProtocolsEnum;
})(hanlder || (hanlder = {}));
//# sourceMappingURL=ProtocolsEnum.js.map