declare module Pan3d {
    class Scene_data {
        static isPanGm: boolean;
        static isPc: boolean;
        static isIos: boolean;
        static context3D: Context3D;
        static canvas3D: HTMLCanvasElement;
        static stageWidth: number;
        static stageHeight: number;
        static sceneViewHW: number;
        static fileRoot: string;
        static ossRoot: string;
        static fileuiRoot: string;
        static verticalScene: boolean;
        static effectsLev: number;
        static cam3D: Camera3D;
        static focus3D: Object3D;
        private static _viewMatrx3D;
        static vpMatrix: Matrix3D;
        static camFar: number;
        static version: number;
        static skyCubeMap: Array<WebGLTexture>;
        static pubLut: WebGLTexture;
        static frameTime: number;
        static MAX_NUMBER: number;
        static uiStage: UIStage;
        static uiBlankStage: UIStage;
        static user: number;
        static light: LightVo;
        static scaleLight: Array<number>;
        static useByte: Boolean;
        static fogColor: Array<number>;
        static fogData: Array<number>;
        static gameAngle: number;
        static sceneNumId: number;
        static fbo: FBO;
        static viewMatrx3D: Matrix3D;
        static supportBlob: boolean;
    }
}
