echo ¿ªÊ¼´ò°üÇÐÆ¬
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_0.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_0.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_1.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_1.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_2.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_2.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_3.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_3.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_4.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_4.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_5.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_5.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_6.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_6.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_7.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_7.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_8.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_8.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_9.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\0_9.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_0.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_0.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_1.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_1.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_2.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_2.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_3.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_3.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_4.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_4.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_5.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_5.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_6.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_6.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_7.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_7.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_8.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_8.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_9.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\1_9.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_0.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_0.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_1.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_1.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_2.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_2.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_3.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_3.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_4.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_4.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_5.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_5.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_6.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_6.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_7.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_7.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_8.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_8.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_9.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\2_9.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_0.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_0.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_1.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_1.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_2.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_2.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_3.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_3.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_4.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_4.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_5.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_5.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_6.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_6.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_7.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_7.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_8.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_8.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_9.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\3_9.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_0.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_0.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_1.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_1.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_2.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_2.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_3.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_3.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_4.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_4.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_5.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_5.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_6.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_6.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_7.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_7.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_8.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_8.bin
D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\mapeditor\tool\png2atf.exe -c d -n 0,0 -i  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_9.jpg  -o  D:\Program Files (x86)\´óºÚµØÍ¼±à¼­Æ÷\scene\1\maps\4_9.bin
echo ´ò°üÍê±ÏÇëµ½sceneÄ¿Â¼ÏÂÌá½»: 1 ÎÄ¼þ¼Ð
pause