declare module prop {
    class ReflectionData {
        static Key_Type: string;
        static Key_GetFun: string;
        static Key_SetFun: string;
        static Key_GetView: string;
        static Key_Data: string;
        static Key_Label: string;
        static Key_Category: string;
        static Key_Suffix: string;
        static Key_Step: string;
        static Key_MaxNum: string;
        static Key_MinNum: string;
        static Key_Tip: string;
        static Key_GetMaxNumFun: string;
        static Key_GetMinNumFun: string;
        static Key_SelectIndex: string;
        static NumberInput: string;
        static CaptureIdUi: string;
        static TEXT: string;
        static Num: string;
        static Input: string;
        static ComboBox: string;
        static ColorPick: string;
        static CheckBox: string;
        static Line: string;
        static Vec3: string;
        static Vec2: string;
        static Btn: string;
        static Texturue2DUI: string;
        static MaterialPicUi: string;
        static RoleMesh2DUI: string;
        static RoleAnim2DUI: string;
        static AgalFunUI: string;
        static Vec3Color: string;
        static Vec2Prama: string;
        static UserView: string;
        static FunKey: string;
        static ClikEventKey: string;
        static Number: string;
    }
}
