declare module Pan3d {
    class PuiData {
        /** 方形高亮64*64 */
        static A_HIGHT_F: string;
        /** tab高亮边框10*10 */
        static TAB_HIGHT: string;
        /** 圆形高亮75*75 */
        static A_HIGHT_C: string;
        /** 关闭按钮43*41 */
        static A_DELETEBTN: string;
        /** 真气图标27*27 */
        static A_ZHENQI: string;
        /** 兽灵图标27*27 */
        static A_SHOULING: string;
        /** 精华图标27*27 */
        static A_JINGHUA: string;
        /** 箭头36*44 */
        static A_JIANTOU: string;
        /** 物品框44*44 */
        static A_WUPINKUANG: string;
        /** 圆形黑框69*69 */
        static A_BLACK_C: string;
        /** 方形黑框64*64 */
        static A_BLACK_F: string;
        /** 黑色星星28*28 */
        static A_BLACK_START: string;
        /** 亮色星星28*28 */
        static A_HIGHT_START: string;
        /** 圆形头像底色71*71 */
        static A_BLACK_BASE: string;
        /** 红点17*16 */
        static A_RED_POINT: string;
        /** 银币25*23 */
        static A_YINBI: string;
        /** 元宝25*23 */
        static A_YUANBAO: string;
        /** 帮贡25*25 */
        static A_BANGGONG: string;
        /** 斗魂25*25 */
        static A_DOUHUN: string;
        /** 经验25*25 */
        static A_EXP: string;
        /** 荣誉25*25 */
        static A_HONOR: string;
        /** 绑定元宝25*23 */
        static A_BANGYUAN: string;
        /** 右边括号25*19 */
        static A_RIGHT_XING: string;
        /** 单独一个星字18*19 */
        static A_SSTART: string;
        /** 左边括号8*19 */
        static A_LEFT_XING: string;
        /** 武器紫色62*62 */
        static A_GOODS_PURPLE: string;
        /** 武器蓝色62*62 */
        static A_GOODS_BLUE: string;
        /** 武器红色62*62 */
        static A_GOODS_RED: string;
        /** 武器绿色62*62 */
        static A_GOODS_GREEN: string;
        /** 武器白色62*62 */
        static A_GOODS_WHITE: string;
        /** 武器橙色62*62 */
        static A_GOODS_ORANGE: string;
        /** 金星背景24*23 */
        static A_START_BG: string;
        /** 金星24*23 */
        static A_START: string;
        /** 链条65*65 */
        static A_CHAIN: string;
        /** 已装备26*56 */
        static A_OK: string;
        /** 前往按钮78*46 */
        static A_QIANWANG: string;
        /** T左31*62 */
        static T_LEFT: string;
        /** T中8*62 */
        static T_MID: string;
        /** T右60*62 */
        static T_RIGHT: string;
        /** E左31*62 */
        static E_LEFT: string;
        /** E中8*62 */
        static E_MID: string;
        /** E右60*62 */
        static E_RIGHT: string;
        /** F左31*62 */
        static F_LEFT: string;
        /** F中8*62 */
        static F_MID: string;
        /** F右60*62 */
        static F_RIGHT: string;
        /** 22*22的物品框 */
        static A_F_22: string;
        /** 66*66的人物头像框 */
        static A_BLACK_BASE_66: string;
        /** 66*66的人物头像框亮 */
        static A_HIGHR_C_66: string;
        /** 22*19Vip的V */
        static A_V: string;
        /** 8*8赠送物品格的背景 */
        static A_GIVING_BG: string;
        /** 24*24减号 */
        static B_SUB: string;
        /** 90*90家族头像底框 */
        static A_FACTION_ICON: string;
        /** 30*30选中勾选框 */
        static SELECT_1: string;
        /** 30*30未选中勾选框 */
        static SELECT_0: string;
        /** 15*16排行榜用到的阶字 */
        static A_JIE: string;
        /** 15*16排行榜用到的星字 */
        static A_XING: string;
        /** 系统提示文字北京 */
        static T_tips_txt_bg: string;
        /** Item底51*51 */
        static ITEMBG: string;
        /** 左边任务背景 */
        static A_quest_top: string;
        static A_quest_mid: string;
        static A_quest_bottom: string;
        /** 左边任务<主> */
        static A_quest_ion0: string;
        /** 左边任务<支> */
        static A_quest_ion1: string;
        /** 左边任务<奇> */
        static A_quest_ion2: string;
        /** 左边任务<活> */
        static A_quest_ion3: string;
        /** 左边任务<完成> */
        static A_quest_finish: string;
        static S_sys_tip0: string;
        static S_sys_tip1: string;
        /** 站力文字 */
        static A_zhanli_label: string;
        static A_gou: string;
        static A_cha: string;
        /** 战斗飘字 50*25 */
        static TYPE3: string;
        static TYPE5: string;
        static TYPE9: string;
        static TYPE7: string;
        static B_ZHUFUZHI: string;
        static B_DABAOJI: string;
        static B_XIAOBAOJI: string;
        static B_JINGYAN: string;
        static NewPicBg: string;
        static Select: string;
        static CostBg: string;
        static BG2: string;
        static PropBg40: string;
        static PropBg60: string;
        static PropBg100: string;
        static REWARD_BG1: string;
        static SKILL_BG68: string;
        static SKILL_BG58: string;
        static BG6: string;
        static Slist_nselect: string;
        static Slist_select: string;
        static TXTBG: string;
        static ARROW_TOP: string;
        static ARROW_RIGHT: string;
        static MASK: string;
        static BTNADD: string;
        static BOSSBG76: string;
        static BOSSBG64: string;
        static CIRCL74: string;
        static LISTITEMBG: string;
        static ADDITEM: string;
        static HASSEL: string;
        static SKILL_LEV_BG: string;
        static TITLEBG: string;
        static TITLEHIGHT: string;
        static NEWLISTITEMBG: string;
        static CHATBG: string;
        static ITEMBIGBG: string;
        static I1bg_2: string;
        static I1bg_1: string;
        static ARROWUP: string;
        static ARROWDOWN: string;
        static A_EQULEVBG: string;
        static DISABLE: string;
        static EQUBG: string;
        static RESLISTBG: string;
        static A_CARD_C: string;
        static A_CARD_G: string;
        static A_CARD_B: string;
        static RESBG: string;
        static STATEUP_LISTBG: string;
        static A_LEAGUELISTBG: string;
        static TEAMLISTBG: string;
        static A_JJ0: string;
        static A_JJ1: string;
        static A_JJ2: string;
        static A_JJ3: string;
        static A_JJ4: string;
        static A_JJ5: string;
        static A_JJ6: string;
        static A_JJ7: string;
        static A_JJ8: string;
        static A_JJ9: string;
        static A_JJ10: string;
    }
}
